[workspace]
resolver = "2"
members = ["src/lib/*", "src/bin/*", "src/wasm/*"]
default-members = ["src/lib/*", "src/bin/*"]

[workspace.package]
description = "OMW = OpenAI + MCP + WASM"
repository = "https://github.com/haras-unicorn/omw"
authors = ["haras-unicorn <github@haras-unicorn.net>"]
license = "MIT"
readme = "./README.md"
edition = "2024"

[workspace.dependencies]
wit-bindgen = "0.61.1"
wasmtime = { version = "48.0.1", features = ["component-model"] }
wasmtime-wasi = "48.0.1"
wat = { version = "1.258.0", features = ["component-model"] }
wasmprinter = "0.258.0"
anyhow = "1.0.104"
tokio = { version = "1.53.1", features = [
  "fs",
  "io-util",
  "macros",
  "net",
  "process",
  "rt-multi-thread",
  "signal",
  "sync",
  "time",
] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = [
  "env-filter",
  "chrono",
  "json",
] }
tracing-journald = "0.3.2"
schemars = "1.2.2"
rustls = { version = "0.23", default-features = false, features = [
  "ring",
  "std",
  "tls12",
] }
serde_json = "1.0.151"
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.6"
serde_norway = "0.9.42"
clap = { version = "4.6.6", features = ["derive"] }
config = { version = "0.15.25" }
nix = "0.31.3"
serial_test = "4.0.1"
tempfile = "3.27.0"
assert_cmd = { version = "2.2.2", features = ["color-auto"] }
predicates = "3.1.4"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
strip = true

[profile.ci]
inherits = "release"
lto = false
codegen-units = 16
opt-level = 1

[profile.dev]
debug = 1

[profile.dev.package."*"]
opt-level = 3
