// The WASM component export ABI generated by `export!` necessarily uses
// `unsafe` (`#[unsafe(export_name)]` shims), so `unsafe_code` cannot be denied
// in this crate.
#![deny(
  clippy::unwrap_used,
  clippy::expect_used,
  clippy::panic,
  clippy::unreachable
)]
#![deny(clippy::arithmetic_side_effects)]
#![deny(clippy::todo)]
#![deny(clippy::allow_attributes_without_reason)]
#![no_main]

//! The bundled test component, built on the `omw-wasm-rust` SDK.
//!
//! Compiles to `wasm32-wasip2` and exports `omw:omw/runtime`: `run(script)`
//! prints a simple "Hello, world!".

omw_wasm_rust::brain!(|| {
  println!("Hello, world!");
  Ok(())
});
