// The WASM component export ABI generated by `export!` necessarily uses
// `unsafe` (`#[unsafe(export_name)]` shims), so `unsafe_code` cannot be denied
// in this crate.
#![deny(
  clippy::unwrap_used,
  clippy::expect_used,
  clippy::panic,
  clippy::unreachable
)]
#![deny(clippy::arithmetic_side_effects)]
#![deny(clippy::todo)]
#![deny(clippy::allow_attributes_without_reason)]
#![no_main]

//! The bundled test component.
//!
//! Compiles to `wasm32-wasip2` and exports `omw:omw/runtime`: `run(script)`
//! prints a simple "Hello, world!".

wit_bindgen::generate!({
    world: "omw",
    path: "../../native/omw/wit",
});

/// The `runtime` interface is our export.
use crate::exports::omw::omw::runtime::Guest;

/// Our exported world implementation.
struct Component;

impl Guest for Component {
  fn kind() -> String {
    "wasm".to_string()
  }

  fn run(_script: String) -> Result<Option<String>, String> {
    println!("Hello, world!");
    Ok(None)
  }
}

export!(Component);
