//! Best-effort conversion of a deployment [`Config`] into a test config whose
//! provider, tooling and endpoint are the in-config `kind = "mock"` doubles.
//!
//! The real back ends are introspected through their registries: a provider's
//! model list is fetched, a tooling's tools and resources are enumerated (and
//! each resource's content read, unless disabled), and everything else in the
//! config is copied through verbatim. Introspection is best-effort: a back end
//! that cannot be built or enumerated yields an empty mock instead of failing
//! the conversion, and the original params — secrets included — never reach the
//! output.

use std::collections::BTreeMap;

use anyhow::{Context as _, Result};

use crate::agent::Registries;
use crate::config::{AgentConfig, Config, ImplConfig, Tunables};
use crate::tooling::{ResourceInfo, Tool};

/// A short backoff for the introspection dial, so an unreachable server fails
/// quickly instead of exhausting the default cap.
fn introspection_tunables(config: &Config) -> Tunables {
  let mut tunables = config.tunables;
  tunables.tooling_connect_backoff_start_ms = 100;
  tunables.tooling_connect_backoff_cap_secs = 1;
  tunables
}

/// Convert `config` into an `omw.test.toml` document. When `resources` is
/// false, tooling resources are not enumerated or read.
pub async fn scaffold(
  config: &Config,
  registries: &Registries,
  resources: bool,
) -> Result<String> {
  let mut root = toml::Table::new();
  root.insert(
    "providers".to_string(),
    mock_providers(config, registries).await?,
  );
  root.insert(
    "tooling".to_string(),
    mock_tooling(config, registries, resources).await?,
  );
  if let Some(endpoint) = mock_endpoint(config) {
    root.insert("endpoint".to_string(), endpoint);
  }
  root.insert("runtime".to_string(), runtime_map(&config.runtime)?);
  if !config.memory.is_empty() {
    root.insert("memory".to_string(), memory_map(&config.memory));
  }
  root.insert("agents".to_string(), agents_array(&config.agents));
  root.insert("tunables".to_string(), tunables_value(&config.tunables));
  let body = toml::to_string_pretty(&toml::Value::Table(root))
    .context("failed to serialize the scaffolded config")?;
  Ok(format!("{HEADER}\n{body}"))
}

const HEADER: &str = "\
# Generated by `omw scaffold`. Best-effort conversion of a deployment config
# into an `omw.test.toml`: provider/tooling/endpoint are the in-config mocks,
# pre-populated from the real back ends where possible. Fill in the provider
# `turns`, tooling `tool_calls`, and endpoint `requests` to script the run.";

/// Rewrite every provider to the mock, keeping the models the real provider
/// reported (empty on any failure).
async fn mock_providers(
  config: &Config,
  registries: &Registries,
) -> Result<toml::Value> {
  let mut table = toml::Table::new();
  for name in sorted_keys(&config.providers) {
    let entry = config
      .providers
      .get(name)
      .context("provider vanished during scaffolding")?;
    let models =
      match registries.providers.build(name, &entry.kind, &entry.params) {
        Ok(built) => match built.inner().list_models().await {
          Ok(models) => models,
          Err(error) => {
            tracing::warn!(
              provider = name,
              error = %error,
              "could not list models for scaffolding; emitting none"
            );
            Vec::new()
          }
        },
        Err(error) => {
          tracing::warn!(
            provider = name,
            error = %error,
            "could not build provider for scaffolding; emitting an empty mock"
          );
          Vec::new()
        }
      };
    let mut provider = toml::Table::new();
    provider
      .insert("kind".to_string(), toml::Value::String("mock".to_string()));
    provider.insert("models".to_string(), string_array(&models));
    provider.insert("turns".to_string(), toml::Value::Array(Vec::new()));
    table.insert(name.clone(), toml::Value::Table(provider));
  }
  Ok(toml::Value::Table(table))
}

/// Rewrite every tooling to the mock, pre-populating its tools and resources
/// from the real back end (best-effort).
async fn mock_tooling(
  config: &Config,
  registries: &Registries,
  resources: bool,
) -> Result<toml::Value> {
  let tunables = introspection_tunables(config);
  let mut table = toml::Table::new();
  for name in sorted_keys(&config.tooling) {
    let entry = config
      .tooling
      .get(name)
      .context("tooling vanished during scaffolding")?;
    let mut tools = Vec::new();
    let mut resource_list = Vec::new();
    let mut resource_contents = BTreeMap::new();
    match registries
      .tooling
      .build(name, &entry.kind, &entry.params, tunables)
    {
      Ok(built) => {
        let tooling = built.inner();
        match tooling.list_tools().await {
          Ok(list) => tools = list,
          Err(error) => tracing::warn!(
            tooling = name,
            error = %error,
            "could not list tools for scaffolding; emitting none"
          ),
        }
        if resources {
          match tooling.list_resources().await {
            Ok(list) => {
              for resource in &list {
                match tooling.read_resource(&resource.uri).await {
                  Ok(content) => {
                    resource_contents
                      .insert(resource.uri.clone(), content.content);
                  }
                  Err(error) => tracing::warn!(
                    tooling = name,
                    uri = %resource.uri,
                    error = %error,
                    "could not read resource for scaffolding; skipping its content"
                  ),
                }
              }
              resource_list = list;
            }
            Err(error) => tracing::warn!(
              tooling = name,
              error = %error,
              "could not list resources for scaffolding; emitting none"
            ),
          }
        }
      }
      Err(error) => tracing::warn!(
        tooling = name,
        error = %error,
        "could not build tooling for scaffolding; emitting an empty mock"
      ),
    }
    let mut mock = toml::Table::new();
    mock.insert("kind".to_string(), toml::Value::String("mock".to_string()));
    mock.insert("tools".to_string(), tools_array(&tools));
    mock.insert(
      "initial_resource_list".to_string(),
      resource_list_array(&resource_list),
    );
    mock.insert(
      "initial_resource_contents".to_string(),
      string_map(&resource_contents),
    );
    mock.insert("tool_calls".to_string(), toml::Value::Array(Vec::new()));
    table.insert(name.clone(), toml::Value::Table(mock));
  }
  Ok(toml::Value::Table(table))
}

/// Rewrite the endpoint to the mock (no request data is discoverable).
fn mock_endpoint(config: &Config) -> Option<toml::Value> {
  config.endpoint.as_ref()?;
  let mut endpoint = toml::Table::new();
  endpoint.insert("kind".to_string(), toml::Value::String("mock".to_string()));
  endpoint.insert("requests".to_string(), toml::Value::Array(Vec::new()));
  Some(toml::Value::Table(endpoint))
}

/// Copy the runtime entries through verbatim (kind plus opaque params).
fn runtime_map(
  runtime: &std::collections::HashMap<String, ImplConfig>,
) -> Result<toml::Value> {
  let mut table = toml::Table::new();
  for name in sorted_keys(runtime) {
    let entry = runtime
      .get(name)
      .context("runtime vanished during scaffolding")?;
    let mut value = toml::Table::new();
    value.insert("kind".to_string(), toml::Value::String(entry.kind.clone()));
    if let Some(params) = entry.params.as_object() {
      for (key, param) in params {
        value.insert(key.clone(), json_to_toml(param)?);
      }
    }
    table.insert(name.clone(), toml::Value::Table(value));
  }
  Ok(toml::Value::Table(table))
}

/// Copy the seeded memory through verbatim.
fn memory_map(
  memory: &BTreeMap<String, BTreeMap<String, String>>,
) -> toml::Value {
  let mut table = toml::Table::new();
  for (agent, entries) in memory {
    table.insert(agent.clone(), string_map(entries));
  }
  toml::Value::Table(table)
}

/// Copy the agents through verbatim.
fn agents_array(agents: &[AgentConfig]) -> toml::Value {
  let mut array = Vec::new();
  for agent in agents {
    let mut table = toml::Table::new();
    table.insert("name".to_string(), toml::Value::String(agent.name.clone()));
    table.insert(
      "runtime".to_string(),
      toml::Value::String(agent.runtime.clone()),
    );
    table.insert(
      "script".to_string(),
      toml::Value::String(agent.script.clone()),
    );
    array.push(toml::Value::Table(table));
  }
  toml::Value::Array(array)
}

/// Copy the tunables through verbatim.
fn tunables_value(tunables: &Tunables) -> toml::Value {
  toml::Value::try_from(*tunables)
    .unwrap_or_else(|_| toml::Value::Table(toml::Table::new()))
}

fn tools_array(tools: &[Tool]) -> toml::Value {
  let mut array = Vec::new();
  for tool in tools {
    let mut table = toml::Table::new();
    table.insert("name".to_string(), toml::Value::String(tool.name.clone()));
    if let Some(description) = &tool.description {
      table.insert(
        "description".to_string(),
        toml::Value::String(description.clone()),
      );
    }
    let input_schema = match json_to_toml(&tool.input_schema) {
      Ok(value) => value,
      Err(error) => {
        tracing::warn!(
          tool = %tool.name,
          error = %error,
          "could not represent a tool's input schema as TOML; emitting an empty schema"
        );
        toml::Value::Table(toml::Table::new())
      }
    };
    table.insert("input_schema".to_string(), input_schema);
    array.push(toml::Value::Table(table));
  }
  toml::Value::Array(array)
}

fn resource_list_array(resources: &[ResourceInfo]) -> toml::Value {
  let mut array = Vec::new();
  for resource in resources {
    let mut table = toml::Table::new();
    table.insert("uri".to_string(), toml::Value::String(resource.uri.clone()));
    table.insert(
      "name".to_string(),
      toml::Value::String(resource.name.clone()),
    );
    if let Some(description) = &resource.description {
      table.insert(
        "description".to_string(),
        toml::Value::String(description.clone()),
      );
    }
    if let Some(mime_type) = &resource.mime_type {
      table.insert(
        "mime_type".to_string(),
        toml::Value::String(mime_type.clone()),
      );
    }
    array.push(toml::Value::Table(table));
  }
  toml::Value::Array(array)
}

fn string_array(values: &[String]) -> toml::Value {
  toml::Value::Array(
    values
      .iter()
      .map(|value| toml::Value::String(value.clone()))
      .collect(),
  )
}

fn string_map(map: &BTreeMap<String, String>) -> toml::Value {
  let mut table = toml::Table::new();
  for (key, value) in map {
    table.insert(key.clone(), toml::Value::String(value.clone()));
  }
  toml::Value::Table(table)
}

/// Convert a JSON value to TOML, failing on shapes TOML cannot represent
/// (notably `null`).
fn json_to_toml(value: &serde_json::Value) -> Result<toml::Value> {
  toml::Value::try_from(value.clone())
    .context("value is not representable as TOML")
}

fn sorted_keys<T>(map: &std::collections::HashMap<String, T>) -> Vec<&String> {
  let mut keys: Vec<&String> = map.keys().collect();
  keys.sort();
  keys
}

#[cfg(test)]
mod tests {
  use super::*;
  use std::sync::Arc;

  use async_trait::async_trait;
  use serde_json::json;

  use crate::provider::{
    ChatDelta, ChatMessage, Factory as ProviderFactory, Provider,
  };
  use crate::tooling::{
    Factory as ToolingFactory, ResourceContent, ResourceInfo, Tool, Tooling,
  };

  struct FakeProvider;

  #[async_trait]
  impl Provider for FakeProvider {
    fn kind() -> &'static str {
      "scaffold-fake"
    }

    async fn list_models(&self) -> anyhow::Result<Vec<String>> {
      Ok(vec!["model-a".to_string(), "model-b".to_string()])
    }

    async fn chat_stream(
      &self,
      _model: &str,
      _messages: Vec<ChatMessage>,
      _tools: Vec<Tool>,
    ) -> anyhow::Result<
      futures_util::stream::BoxStream<'static, Result<ChatDelta, String>>,
    > {
      Ok(Box::pin(futures_util::stream::empty()))
    }
  }

  impl ProviderFactory for FakeProvider {
    fn build(
      _name: &str,
      _params: &serde_json::Value,
    ) -> anyhow::Result<Arc<Self>> {
      Ok(Arc::new(FakeProvider))
    }
  }

  struct FailingProvider;

  #[async_trait]
  impl Provider for FailingProvider {
    fn kind() -> &'static str {
      "scaffold-failing-provider"
    }

    async fn list_models(&self) -> anyhow::Result<Vec<String>> {
      anyhow::bail!("no models here")
    }

    async fn chat_stream(
      &self,
      _model: &str,
      _messages: Vec<ChatMessage>,
      _tools: Vec<Tool>,
    ) -> anyhow::Result<
      futures_util::stream::BoxStream<'static, Result<ChatDelta, String>>,
    > {
      anyhow::bail!("nope")
    }
  }

  impl ProviderFactory for FailingProvider {
    fn build(
      _name: &str,
      _params: &serde_json::Value,
    ) -> anyhow::Result<Arc<Self>> {
      Ok(Arc::new(FailingProvider))
    }
  }

  struct FakeTooling;

  #[async_trait]
  impl Tooling for FakeTooling {
    fn kind() -> &'static str {
      "scaffold-fake"
    }

    async fn list_tools(&self) -> anyhow::Result<Vec<Tool>> {
      Ok(vec![Tool {
        name: "echo".to_string(),
        description: Some("echoes".to_string()),
        input_schema: json!({
          "type": "object",
          "properties": { "input": { "type": "string" } },
        }),
      }])
    }

    async fn call_tool(
      &self,
      _name: &str,
      _args: serde_json::Value,
    ) -> anyhow::Result<String> {
      Ok(String::new())
    }

    async fn list_resources(&self) -> anyhow::Result<Vec<ResourceInfo>> {
      Ok(vec![ResourceInfo {
        uri: "mem://notes".to_string(),
        name: "notes".to_string(),
        description: None,
        mime_type: Some("text/plain".to_string()),
      }])
    }

    async fn read_resource(
      &self,
      uri: &str,
    ) -> anyhow::Result<ResourceContent> {
      Ok(ResourceContent {
        uri: uri.to_string(),
        mime_type: Some("text/plain".to_string()),
        content: "v1".to_string(),
      })
    }

    async fn subscribe_resource_list(
      &self,
    ) -> anyhow::Result<
      futures_util::stream::BoxStream<
        'static,
        Result<crate::tooling::ResourceNotification, String>,
      >,
    > {
      Ok(Box::pin(futures_util::stream::empty()))
    }

    async fn subscribe_resource(
      &self,
      _uri: &str,
    ) -> anyhow::Result<
      futures_util::stream::BoxStream<
        'static,
        Result<crate::tooling::ResourceNotification, String>,
      >,
    > {
      Ok(Box::pin(futures_util::stream::empty()))
    }
  }

  impl ToolingFactory for FakeTooling {
    fn build(
      _name: &str,
      _params: &serde_json::Value,
      _tunables: Tunables,
    ) -> anyhow::Result<Arc<Self>> {
      Ok(Arc::new(FakeTooling))
    }
  }

  struct FailingTooling;

  #[async_trait]
  impl Tooling for FailingTooling {
    fn kind() -> &'static str {
      "scaffold-failing"
    }

    async fn list_tools(&self) -> anyhow::Result<Vec<Tool>> {
      anyhow::bail!("no tools here")
    }

    async fn call_tool(
      &self,
      _name: &str,
      _args: serde_json::Value,
    ) -> anyhow::Result<String> {
      anyhow::bail!("nope")
    }

    async fn list_resources(&self) -> anyhow::Result<Vec<ResourceInfo>> {
      anyhow::bail!("no resources here")
    }

    async fn read_resource(
      &self,
      _uri: &str,
    ) -> anyhow::Result<ResourceContent> {
      anyhow::bail!("nope")
    }

    async fn subscribe_resource_list(
      &self,
    ) -> anyhow::Result<
      futures_util::stream::BoxStream<
        'static,
        Result<crate::tooling::ResourceNotification, String>,
      >,
    > {
      anyhow::bail!("nope")
    }

    async fn subscribe_resource(
      &self,
      _uri: &str,
    ) -> anyhow::Result<
      futures_util::stream::BoxStream<
        'static,
        Result<crate::tooling::ResourceNotification, String>,
      >,
    > {
      anyhow::bail!("nope")
    }
  }

  impl ToolingFactory for FailingTooling {
    fn build(
      _name: &str,
      _params: &serde_json::Value,
      _tunables: Tunables,
    ) -> anyhow::Result<Arc<Self>> {
      Ok(Arc::new(FailingTooling))
    }
  }

  fn registries() -> anyhow::Result<Registries> {
    let mut registries = Registries::default();
    registries.providers.register::<FakeProvider>()?;
    registries.providers.register::<FailingProvider>()?;
    registries.tooling.register::<FakeTooling>()?;
    registries.tooling.register::<FailingTooling>()?;
    Ok(registries)
  }

  fn config() -> Config {
    toml::from_str(
      r#"
        [providers.real]
        kind = "scaffold-fake"
        api_key = "sk-secret"

        [providers.broken]
        kind = "scaffold-failing-provider"

        [tooling.docs]
        kind = "scaffold-fake"
        token = "secret-token"

        [tooling.broken]
        kind = "scaffold-failing"

        [endpoint]
        kind = "openai"
        listen = "127.0.0.1:8080"

        [runtime.rhai]
        kind = "rhai"

        [memory.alice]
        handle = "seed-42"

        [[agents]]
        name = "alice"
        runtime = "rhai"
        script = "brain.rhai"

        [tunables]
        recv_timeout_secs = 30
      "#,
    )
    .expect("test config should parse")
  }

  #[tokio::test]
  async fn rewrites_backends_to_mocks_and_prepopulates() -> anyhow::Result<()> {
    let out = scaffold(&config(), &registries()?, true).await?;
    assert!(!out.contains("sk-secret"), "{out}");
    assert!(!out.contains("secret-token"), "{out}");

    let parsed: Config = toml::from_str(&out)?;
    assert_eq!(parsed.providers["real"].kind, "mock");
    assert_eq!(
      parsed.providers["real"].params["models"],
      json!(["model-a", "model-b"])
    );
    assert_eq!(parsed.tooling["docs"].kind, "mock");
    assert_eq!(parsed.tooling["docs"].params["tools"][0]["name"], "echo");
    assert_eq!(
      parsed.tooling["docs"].params["initial_resource_contents"]["mem://notes"],
      "v1"
    );
    assert_eq!(
      parsed.tooling["docs"].params["initial_resource_list"][0]["uri"],
      "mem://notes"
    );
    assert_eq!(
      parsed.endpoint.as_ref().map(|e| e.kind.as_str()),
      Some("mock")
    );
    assert_eq!(parsed.agents[0].name, "alice");
    assert_eq!(parsed.memory["alice"]["handle"], "seed-42");
    assert_eq!(parsed.tunables.recv_timeout_secs, 30);

    assert!(out.contains("[[agents]]"), "{out}");
    assert!(!out.contains("[assertions"), "{out}");
    Ok(())
  }

  #[tokio::test]
  async fn failures_are_best_effort() -> anyhow::Result<()> {
    let out = scaffold(&config(), &registries()?, true).await?;
    let parsed: Config = toml::from_str(&out)?;
    assert_eq!(parsed.providers["broken"].kind, "mock");
    assert_eq!(parsed.providers["broken"].params["models"], json!([]));
    assert_eq!(parsed.tooling["broken"].kind, "mock");
    assert_eq!(parsed.tooling["broken"].params["tools"], json!([]));
    Ok(())
  }

  #[tokio::test]
  async fn no_resources_skips_resource_population() -> anyhow::Result<()> {
    let out = scaffold(&config(), &registries()?, false).await?;
    let parsed: Config = toml::from_str(&out)?;
    assert_eq!(
      parsed.tooling["docs"].params["initial_resource_list"],
      json!([])
    );
    assert_eq!(
      parsed.tooling["docs"].params["initial_resource_contents"],
      json!({})
    );
    assert_eq!(parsed.tooling["docs"].params["tools"][0]["name"], "echo");
    Ok(())
  }

  #[tokio::test]
  async fn output_is_a_valid_test_config() -> anyhow::Result<()> {
    let out = scaffold(&config(), &registries()?, true).await?;
    let parsed: Config = toml::from_str(&out)?;
    crate::testing::parse(&out).context("assertions should parse")?;
    for (name, entry) in &parsed.tooling {
      let built = crate::tooling::Registry::default().build(
        name,
        &entry.kind,
        &entry.params,
        Tunables::default(),
      )?;
      assert_eq!(built.kind(), "mock");
    }
    Ok(())
  }
}
