// The WASM component export ABI generated by `export!` necessarily uses
// `unsafe` (`#[unsafe(export_name)]` shims), so `unsafe_code` cannot be denied
// in this crate.
#![deny(
  clippy::unwrap_used,
  clippy::expect_used,
  clippy::panic,
  clippy::unreachable
)]
#![deny(clippy::arithmetic_side_effects)]
#![deny(clippy::todo)]
#![deny(clippy::allow_attributes_without_reason)]
#![no_main]

//! The bundled Python evaluator component.
//!
//! Compiles to `wasm32-wasip2` and exports `omw:omw/runtime`: `run(script)`
//! evaluates the agent's `.py` script on a [RustPython] interpreter. Inside a
//! script, the `omw` global holds three namespaces mirroring the rhai/js
//! interpreters: `provider` / `tooling` / `host`.
//!
//! Provider/tooling instances are looked up by name with `get`, which returns
//! an object holding the configured name plus its methods, so scripts call
//! them method-style (`p.chat(...)`, `t.call_tool(...)`), snake_case only.
//!
//! [RustPython]: https://rustpython.github.io

wit_bindgen::generate!({
    world: "omw",
    path: "wit",
});

mod convert;
mod host;
mod provider;
mod tooling;

use rustpython_vm::builtins::{PyBaseExceptionRef, PyNone};
use rustpython_vm::compiler::Mode;
use rustpython_vm::{
  Interpreter, PyObjectRef, PyResult, Settings, VirtualMachine,
};

/// Our exported world implementation.
struct Component;

impl crate::exports::omw::omw::runtime::Guest for Component {
  fn kind() -> String {
    "python".to_string()
  }

  fn run(script: String) -> Result<Option<String>, String> {
    eval(&script)
  }

  fn check(script: String) -> Result<(), String> {
    parse(&script)
  }
}

export!(Component);

/// Build a fresh interpreter with the frozen standard library and the native
/// stdlib modules. One interpreter per component instance is enough: the host
/// instantiates a new component for every `run`/`check`.
fn build_interpreter() -> Interpreter {
  let builder = Interpreter::builder(Settings::default());
  let modules = rustpython_stdlib::stdlib_module_defs(&builder.ctx);
  builder
    .add_native_modules(&modules)
    .add_frozen_modules(rustpython_pylib::FROZEN_STDLIB)
    .build()
}

/// Render a Python exception as a plain string, without a traceback.
fn exception_message(vm: &VirtualMachine, error: PyBaseExceptionRef) -> String {
  let (_, value, _) = vm.split_exception(error);
  match value.repr(vm) {
    Ok(text) => text.to_string_lossy().into_owned(),
    Err(_) => "python exception".to_owned(),
  }
}

/// Install the `omw` global with its `provider` / `tooling` / `host`
/// namespaces, both on `builtins` (so scripts need no import) and in
/// `sys.modules` (so `import omw` also works).
fn install_omw(vm: &VirtualMachine) -> PyResult<()> {
  let host = vm.new_module("omw.host", vm.ctx.new_dict(), None);
  host.set_attr("log", vm.new_function("log", host::host_log), vm)?;
  host.set_attr("whoami", vm.new_function("whoami", host::host_whoami), vm)?;
  host.set_attr(
    "time_now",
    vm.new_function("time_now", host::host_time_now),
    vm,
  )?;
  host.set_attr(
    "time_format",
    vm.new_function("time_format", host::host_time_format),
    vm,
  )?;
  host.set_attr(
    "wait_until",
    vm.new_function("wait_until", host::host_wait_until),
    vm,
  )?;
  host.set_attr(
    "wait_for",
    vm.new_function("wait_for", host::host_wait_for),
    vm,
  )?;
  host.set_attr(
    "wait_cron",
    vm.new_function("wait_cron", host::host_wait_cron),
    vm,
  )?;
  host.set_attr(
    "sleep_for",
    vm.new_function("sleep_for", host::host_sleep_for),
    vm,
  )?;
  host.set_attr(
    "sleep_until",
    vm.new_function("sleep_until", host::host_sleep_until),
    vm,
  )?;
  host.set_attr(
    "sleep_cron",
    vm.new_function("sleep_cron", host::host_sleep_cron),
    vm,
  )?;
  host.set_attr(
    "cancel_timer",
    vm.new_function("cancel_timer", host::host_cancel_timer),
    vm,
  )?;
  host.set_attr(
    "subscribe_agent",
    vm.new_function("subscribe_agent", host::host_subscribe_agent),
    vm,
  )?;
  host.set_attr(
    "unsubscribe_agent",
    vm.new_function("unsubscribe_agent", host::host_unsubscribe_agent),
    vm,
  )?;
  host.set_attr(
    "subscribe_lifecycle",
    vm.new_function("subscribe_lifecycle", host::host_subscribe_lifecycle),
    vm,
  )?;
  host.set_attr(
    "unsubscribe_lifecycle",
    vm.new_function("unsubscribe_lifecycle", host::host_unsubscribe_lifecycle),
    vm,
  )?;
  host.set_attr(
    "send_agent",
    vm.new_function("send_agent", host::host_send_agent),
    vm,
  )?;
  host.set_attr("recv", vm.new_function("recv", host::host_recv), vm)?;
  host.set_attr(
    "try_recv",
    vm.new_function("try_recv", host::host_try_recv),
    vm,
  )?;
  host.set_attr(
    "new_uuid",
    vm.new_function("new_uuid", host::host_new_uuid),
    vm,
  )?;
  host.set_attr(
    "base64_encode",
    vm.new_function("base64_encode", host::host_base64_encode),
    vm,
  )?;
  host.set_attr(
    "base64_decode",
    vm.new_function("base64_decode", host::host_base64_decode),
    vm,
  )?;
  host.set_attr(
    "memory_get",
    vm.new_function("memory_get", host::host_memory_get),
    vm,
  )?;
  host.set_attr(
    "memory_get_as",
    vm.new_function("memory_get_as", host::host_memory_get_as),
    vm,
  )?;
  host.set_attr(
    "memory_set",
    vm.new_function("memory_set", host::host_memory_set),
    vm,
  )?;
  host.set_attr(
    "memory_set_as",
    vm.new_function("memory_set_as", host::host_memory_set_as),
    vm,
  )?;
  host.set_attr(
    "memory_remove",
    vm.new_function("memory_remove", host::host_memory_remove),
    vm,
  )?;
  host.set_attr(
    "subscribe_endpoint",
    vm.new_function("subscribe_endpoint", host::host_subscribe_endpoint),
    vm,
  )?;
  host.set_attr(
    "unsubscribe_endpoint",
    vm.new_function("unsubscribe_endpoint", host::host_unsubscribe_endpoint),
    vm,
  )?;
  host.set_attr(
    "stream_endpoint",
    vm.new_function("stream_endpoint", host::host_stream_endpoint),
    vm,
  )?;

  let provider = vm.new_module("omw.provider", vm.ctx.new_dict(), None);
  provider.set_attr(
    "get",
    vm.new_function("get", provider::provider_get),
    vm,
  )?;

  let tooling = vm.new_module("omw.tooling", vm.ctx.new_dict(), None);
  tooling.set_attr("get", vm.new_function("get", tooling::tooling_get), vm)?;

  let omw = vm.new_module("omw", vm.ctx.new_dict(), None);
  omw.set_attr("host", host.clone(), vm)?;
  omw.set_attr("provider", provider.clone(), vm)?;
  omw.set_attr("tooling", tooling.clone(), vm)?;

  vm.builtins.set_attr("omw", omw.clone(), vm)?;

  let modules = vm.sys_module.get_attr("modules", vm)?;
  modules.set_item("omw", omw.into(), vm)?;
  modules.set_item("omw.host", host.into(), vm)?;
  modules.set_item("omw.provider", provider.into(), vm)?;
  modules.set_item("omw.tooling", tooling.into(), vm)?;
  Ok(())
}

/// Stringify the value of an expression-evaluated brain, if any.
fn stringify(vm: &VirtualMachine, value: &PyObjectRef) -> Option<String> {
  if value.downcast_ref::<PyNone>().is_some() {
    return None;
  }
  value
    .str(vm)
    .ok()
    .map(|text| text.to_string_lossy().into_owned())
}

fn eval(script: &str) -> Result<Option<String>, String> {
  let interpreter = build_interpreter();
  interpreter.enter(|vm| {
    install_omw(vm).map_err(|e| exception_message(vm, e))?;

    // A script that parses as a single expression is evaluated as one, so its
    // value becomes the terminal message; anything else runs as statements.
    if let Ok(code) = vm.compile(script, Mode::Eval, "<brain>") {
      let scope = vm.new_scope_with_builtins();
      let value = vm
        .run_code_obj(code, scope)
        .map_err(|e| exception_message(vm, e))?;
      return Ok(stringify(vm, &value));
    }

    let code = vm
      .compile(script, Mode::Exec, "<brain>")
      .map_err(|e| e.to_string())?;
    let scope = vm.new_scope_with_builtins();
    vm.run_code_obj(code, scope)
      .map_err(|e| exception_message(vm, e))?;
    Ok(None)
  })
}

fn parse(script: &str) -> Result<(), String> {
  let interpreter = build_interpreter();
  interpreter.enter(|vm| {
    vm.compile(script, Mode::Exec, "<brain>")
      .map(|_| ())
      .map_err(|e| e.to_string())
  })
}
