declare namespace OmwConfig {
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  /**
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Secret".
   */
  export type Secret = string;
  /**
   * Filesystem permissions for one [`Preopen`].
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "FsPerms".
   */
  export type FsPerms = "read_only" | "read_write";
  /**
   * Impl-specific configuration for a single MCP server, selected by
   * transport.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Config2".
   */
  export type Config2 =
    | {
        args?: string[];
        command: string;
        env?: {
          [k: string]: Secret;
        };
        transport: "stdio";
        [k: string]: unknown;
      }
    | {
        auth_token?: Secret | null;
        transport: "http";
        url: string;
        [k: string]: unknown;
      };
  /**
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "EndpointImpls".
   */
  export type EndpointImpls =
    | (
        | (Config4 & {
            kind: "openai";
            [k: string]: unknown;
          })
        | ImplConfig
      )
    | null;

  /**
   * OMW configuration.
   */
  export interface Config {
    /**
     * Agents that OMW is going to run, keyed by agent name.
     */
    agents?: {
      [k: string]: AgentConfig;
    };
    /**
     * Optional endpoint implementation.
     */
    endpoint?:
      | (
          | (Config4 & {
              kind: "openai";
              [k: string]: unknown;
            })
          | ImplConfig
        )
      | null;
    /**
     * Per-agent seeded memory, keyed by agent name then key. Seeded into the
     * agent's memory before its brain first runs, so a test (or a deployment)
     * can fast-forward an agent to a state. Seeded values persist like any
     * other memory, including across hot reloads.
     *
     * A value that is a string is stored verbatim; anything else (object,
     * array, number, bool) is JSON-stringified, mirroring `memory-set`. Read it
     * back with `memory-get` (raw) or `memory-get-as` (parsed).
     */
    memory?: {
      [k: string]: {
        [k: string]: unknown;
      };
    };
    providers?: ProviderImpls;
    runtime?: RuntimeImpls;
    tooling?: ToolingImpls;
    tunables?: Tunables;
    [k: string]: unknown;
  }
  /**
   * A single agent wiring itself to the globals above. The agent's name is the
   * key it appears under in [`Config::agents`].
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "AgentConfig".
   */
  export interface AgentConfig {
    /**
     * Which named runtime implementation this agent's brain uses.
     */
    runtime: string;
    /**
     * The agent's brain script.
     */
    script: string;
    [k: string]: unknown;
  }
  /**
   * Impl-specific configuration for the OpenAI-compatible endpoint.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Config4".
   */
  export interface Config4 {
    /**
     * Socket address to listen on, e.g. `"127.0.0.1:8080"` or
     * `"0.0.0.0:8080"`. Hostnames (e.g. `"localhost:8080"`) are rejected at
     * startup.
     */
    listen: string;
    [k: string]: unknown;
  }
  /**
   * A single configured implementation: which kind plus opaque params.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "ImplConfig".
   */
  export interface ImplConfig {
    /**
     * Which implementation this is.
     */
    kind: string;
    [k: string]: unknown;
  }
  /**
   * Named provider implementations.
   */
  export interface ProviderImpls {
    [k: string]:
      | (Config1 & {
          kind: "openai";
          [k: string]: unknown;
        })
      | ImplConfig;
  }
  /**
   * Impl-specific configuration for the OpenAI-family provider.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Config".
   */
  export interface Config1 {
    api_key?: Secret | null;
    base_url?: string | null;
    model?: string | null;
    /**
     * Default generation params merged into every request body (temperature,
     * max_tokens, reasoning_effort, …). Per-call params override these.
     */
    params?: {
      [k: string]: unknown;
    } | null;
    [k: string]: unknown;
  }
  /**
   * Named runtime implementations.
   */
  export interface RuntimeImpls {
    [k: string]:
      | (Config3 & {
          kind: "wasm";
          [k: string]: unknown;
        })
      | ImplConfig;
  }
  /**
   * WASI context configuration for wasm-based runtimes, flattened into each
   * runtime's own config. Deny-by-default, mirroring
   * `WasiCtxBuilder::default()`: no stdio inheritance, no env, no args, no
   * preopens, no network.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Config3".
   */
  export interface Config3 {
    allow_blocking_current_thread?: boolean;
    allow_ip_name_lookup?: boolean;
    allow_tcp?: boolean;
    allow_udp?: boolean;
    args?: string[];
    env?: {
      [k: string]: Secret;
    };
    inherit_args?: boolean;
    inherit_env?: boolean;
    inherit_network?: boolean;
    inherit_stderr?: boolean;
    inherit_stdin?: boolean;
    inherit_stdio?: boolean;
    inherit_stdout?: boolean;
    initial_cwd?: string | null;
    insecure_random_seed?: number | null;
    max_random_size?: number | null;
    preopens?: Preopen[];
    [k: string]: unknown;
  }
  /**
   * One preopened directory: `host_path` on the host, visible to the guest
   * as `guest_path`.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Preopen".
   */
  export interface Preopen {
    guest_path: string;
    host_path: string;
    perms?: FsPerms;
    [k: string]: unknown;
  }
  /**
   * Named tooling implementations.
   */
  export interface ToolingImpls {
    [k: string]:
      | (Config2 & {
          kind: "mcp";
          [k: string]: unknown;
        })
      | ImplConfig;
  }
  /**
   * Global runtime tunables.
   */
  export interface Tunables {
    /**
     * Permit secrets to stay unlocked (pageable) when `mlock` fails, e.g.
     * inside containers where the outer `RLIMIT_MEMLOCK` cannot be raised.
     * Default `false` (fail-closed). Only enable where the weaker guarantee
     * is acceptable.
     */
    allow_unlocked_secrets?: boolean;
    /**
     * Cancel open pumps (streams, timers, resources, tool calls) on reload.
     * `false` keeps them across reload.
     */
    cancel_pumps_on_reload?: boolean;
    /**
     * How many events a single agent inbox buffers before sends fail.
     */
    inbox_bound?: number;
    /**
     * Uninterrupted runtime execution allowed after grace expires, in ms.
     */
    interrupt_budget_ms?: number;
    /**
     * Backoff cap for `loop` restarts on failure, in seconds.
     */
    loop_backoff_cap_secs?: number;
    /**
     * Backoff start for `loop` restarts on failure, in ms.
     */
    loop_backoff_start_ms?: number;
    /**
     * How long `recv_while` parks between early-abort checks, in ms.
     */
    recv_slice_ms?: number;
    /**
     * How long a blocking `recv` waits before timing out, in seconds.
     */
    recv_timeout_secs?: number;
    /**
     * How long the supervisor waits for a cooperative exit, in seconds.
     */
    reload_grace_secs?: number;
    /**
     * How long the blocking-call helper waits between reload checks, in ms.
     */
    reload_poll_ms?: number;
    /**
     * How many deltas a single endpoint session buffers before drops.
     */
    session_buffer?: number;
    /**
     * Backoff cap for tooling reconnects on failure, in seconds.
     */
    tooling_connect_backoff_cap_secs?: number;
    /**
     * Backoff start for tooling reconnects on failure, in ms.
     */
    tooling_connect_backoff_start_ms?: number;
    /**
     * How many trace events the `omw-test` broadcast channel buffers.
     */
    trace_buffer?: number;
    /**
     * How long to coalesce the burst of file events a single save produces,
     * in ms.
     */
    watch_debounce_ms?: number;
    [k: string]: unknown;
  }
  /**
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "ProviderImpls".
   */
  export interface ProviderImpls1 {
    [k: string]:
      | (Config1 & {
          kind: "openai";
          [k: string]: unknown;
        })
      | ImplConfig;
  }
  /**
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "RuntimeImpls".
   */
  export interface RuntimeImpls1 {
    [k: string]:
      | (Config3 & {
          kind: "wasm";
          [k: string]: unknown;
        })
      | ImplConfig;
  }
  /**
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "ToolingImpls".
   */
  export interface ToolingImpls1 {
    [k: string]:
      | (Config2 & {
          kind: "mcp";
          [k: string]: unknown;
        })
      | ImplConfig;
  }
  /**
   * Runtime tunables: channel sizes, timeouts, and backoffs. All optional;
   * omitted values fall back to the built-in defaults.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Tunables".
   */
  export interface Tunables1 {
    /**
     * Permit secrets to stay unlocked (pageable) when `mlock` fails, e.g.
     * inside containers where the outer `RLIMIT_MEMLOCK` cannot be raised.
     * Default `false` (fail-closed). Only enable where the weaker guarantee
     * is acceptable.
     */
    allow_unlocked_secrets?: boolean;
    /**
     * Cancel open pumps (streams, timers, resources, tool calls) on reload.
     * `false` keeps them across reload.
     */
    cancel_pumps_on_reload?: boolean;
    /**
     * How many events a single agent inbox buffers before sends fail.
     */
    inbox_bound?: number;
    /**
     * Uninterrupted runtime execution allowed after grace expires, in ms.
     */
    interrupt_budget_ms?: number;
    /**
     * Backoff cap for `loop` restarts on failure, in seconds.
     */
    loop_backoff_cap_secs?: number;
    /**
     * Backoff start for `loop` restarts on failure, in ms.
     */
    loop_backoff_start_ms?: number;
    /**
     * How long `recv_while` parks between early-abort checks, in ms.
     */
    recv_slice_ms?: number;
    /**
     * How long a blocking `recv` waits before timing out, in seconds.
     */
    recv_timeout_secs?: number;
    /**
     * How long the supervisor waits for a cooperative exit, in seconds.
     */
    reload_grace_secs?: number;
    /**
     * How long the blocking-call helper waits between reload checks, in ms.
     */
    reload_poll_ms?: number;
    /**
     * How many deltas a single endpoint session buffers before drops.
     */
    session_buffer?: number;
    /**
     * Backoff cap for tooling reconnects on failure, in seconds.
     */
    tooling_connect_backoff_cap_secs?: number;
    /**
     * Backoff start for tooling reconnects on failure, in ms.
     */
    tooling_connect_backoff_start_ms?: number;
    /**
     * How many trace events the `omw-test` broadcast channel buffers.
     */
    trace_buffer?: number;
    /**
     * How long to coalesce the burst of file events a single save produces,
     * in ms.
     */
    watch_debounce_ms?: number;
    [k: string]: unknown;
  }
}
