# generated by datamodel-codegen:
#   filename:  schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class AgentConfig(BaseModel):
    runtime: str = Field(
        ..., description="Which named runtime implementation this agent's brain uses."
    )
    script: str = Field(..., description="The agent's brain script.")


class Config4(BaseModel):
    listen: str = Field(
        ...,
        description='Socket address to listen on, e.g. `"127.0.0.1:37532"` or\n`"0.0.0.0:37532"`. Hostnames (e.g. `"localhost:37532"`) are rejected at\nstartup.',
    )


class EndpointImpls1(Config4):
    kind: Literal['openai']


class FsPerms(Enum):
    read_only = 'read_only'
    read_write = 'read_write'


class ImplConfig(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    kind: str = Field(..., description='Which implementation this is.')


class Preopen(BaseModel):
    guest_path: str
    host_path: str
    perms: FsPerms | None = None


class Secret(RootModel[str]):
    root: str


class ToolingImpls11(BaseModel):
    args: list[str] | None = []
    command: str
    env: dict[str, Secret] | None = Field({}, validate_default=True)
    transport: Literal['stdio']


class ToolingImpls12(BaseModel):
    auth_token: Secret | None = None
    transport: Literal['http']
    url: str


class ToolingImpls13(BaseModel):
    kind: Literal['mcp']


class ToolingImpls14(ToolingImpls11, ToolingImpls13):
    pass


class ToolingImpls15(ToolingImpls12, ToolingImpls13):
    pass


class ToolingImpls1(RootModel[ToolingImpls14 | ToolingImpls15]):
    root: ToolingImpls14 | ToolingImpls15


class ToolingImpls(RootModel[dict[str, ToolingImpls1 | ImplConfig]]):
    root: dict[str, ToolingImpls1 | ImplConfig]


class Tunables(BaseModel):
    allow_unlocked_secrets: bool | None = Field(
        False,
        description='Permit secrets to stay unlocked (pageable) when `mlock` fails, e.g.\ninside containers where the outer `RLIMIT_MEMLOCK` cannot be raised.\nDefault `false` (fail-closed). Only enable where the weaker guarantee\nis acceptable.',
    )
    cancel_pumps_on_reload: bool | None = Field(
        True,
        description='Cancel open pumps (streams, timers, resources, tool calls) on reload.\n`false` keeps them across reload.',
    )
    inbox_bound: conint(ge=0) | None = Field(
        1024,
        description='How many events a single agent inbox buffers before sends fail.',
    )
    interrupt_budget_ms: conint(ge=0) | None = Field(
        100,
        description='Uninterrupted runtime execution allowed after grace expires, in ms.',
    )
    loop_backoff_cap_secs: conint(ge=0) | None = Field(
        30, description='Backoff cap for `loop` restarts on failure, in seconds.'
    )
    loop_backoff_start_ms: conint(ge=0) | None = Field(
        100, description='Backoff start for `loop` restarts on failure, in ms.'
    )
    recv_slice_ms: conint(ge=0) | None = Field(
        200,
        description='How long `recv_while` parks between early-abort checks, in ms.',
    )
    recv_timeout_secs: conint(ge=0) | None = Field(
        60,
        description='How long a blocking `recv` waits before timing out, in seconds.',
    )
    reload_grace_secs: conint(ge=0) | None = Field(
        5,
        description='How long the supervisor waits for a cooperative exit, in seconds.',
    )
    reload_poll_ms: conint(ge=0) | None = Field(
        200,
        description='How long the blocking-call helper waits between reload checks, in ms.',
    )
    session_buffer: conint(ge=0) | None = Field(
        8192,
        description='How many deltas a single endpoint session buffers before drops.',
    )
    test_timeout_secs: conint(ge=0) | None = Field(
        30,
        description='How long a single testing-harness run may take before it is force-stopped\nand every unsettled agent marked timed out, in seconds. `0` disables it.',
    )
    tooling_connect_backoff_cap_secs: conint(ge=0) | None = Field(
        30, description='Backoff cap for tooling reconnects on failure, in seconds.'
    )
    tooling_connect_backoff_start_ms: conint(ge=0) | None = Field(
        100, description='Backoff start for tooling reconnects on failure, in ms.'
    )
    trace_buffer: conint(ge=0) | None = Field(
        4096,
        description='How many trace events the `omw-test` broadcast channel buffers.',
    )
    tui_tab_capacity: conint(ge=0) | None = Field(
        2000,
        description='How many log lines each live-view tab keeps before the oldest are\ndropped. `0` means unlimited.',
    )
    tui_tick_ms: conint(ge=0) | None = Field(
        80,
        description="How long the live view's render loop waits between redraws, in ms. It is\nboth the spinner cadence and the maximum redraw interval.",
    )
    watch_debounce_ms: conint(ge=0) | None = Field(
        200,
        description='How long to coalesce the burst of file events a single save produces,\nin ms.',
    )


class Config1(BaseModel):
    api_key: Secret | None = None
    base_url: str | None = None
    model: str | None = None
    params: dict[str, Any] | None = Field(
        None,
        description='Default generation params merged into every request body (temperature,\nmax_tokens, reasoning_effort, …). Per-call params override these.',
    )


class Config21(BaseModel):
    args: list[str] | None = []
    command: str
    env: dict[str, Secret] | None = Field({}, validate_default=True)
    transport: Literal['stdio']


class Config22(BaseModel):
    auth_token: Secret | None = None
    transport: Literal['http']
    url: str


class Config2(RootModel[Config21 | Config22]):
    root: Config21 | Config22 = Field(
        ...,
        description='Impl-specific configuration for a single MCP server, selected by\ntransport.',
    )


class Config3(BaseModel):
    allow_blocking_current_thread: bool | None = False
    allow_ip_name_lookup: bool | None = False
    allow_tcp: bool | None = False
    allow_udp: bool | None = False
    args: list[str] | None = []
    env: dict[str, Secret] | None = Field({}, validate_default=True)
    inherit_args: bool | None = False
    inherit_env: bool | None = False
    inherit_network: bool | None = False
    inherit_stderr: bool | None = False
    inherit_stdin: bool | None = False
    inherit_stdio: bool | None = False
    inherit_stdout: bool | None = False
    initial_cwd: str | None = None
    insecure_random_seed: conint(ge=0) | None = None
    max_random_size: conint(ge=0) | None = None
    preopens: list[Preopen] | None = None


class EndpointImpls(RootModel[EndpointImpls1 | ImplConfig | None]):
    root: EndpointImpls1 | ImplConfig | None


class ProviderImpls1(Config1):
    kind: Literal['openai']


class ProviderImpls(RootModel[dict[str, ProviderImpls1 | ImplConfig]]):
    root: dict[str, ProviderImpls1 | ImplConfig]


class RuntimeImpls1(Config3):
    kind: Literal['wasm']


class RuntimeImpls(RootModel[dict[str, RuntimeImpls1 | ImplConfig]]):
    root: dict[str, RuntimeImpls1 | ImplConfig]


class Config(BaseModel):
    agents: dict[str, AgentConfig] | None = Field(
        {},
        description='Agents that OMW is going to run, keyed by agent name.',
        validate_default=True,
    )
    endpoint: EndpointImpls | None = Field(
        None, description='Optional endpoint implementation.'
    )
    memory: dict[str, dict[str, Any]] | None = Field(
        {},
        description="Per-agent seeded memory, keyed by agent name then key. Seeded into the\nagent's memory before its brain first runs, so a test (or a deployment)\ncan fast-forward an agent to a state. Seeded values persist like any\nother memory, including across hot reloads.\n\nA value that is a string is stored verbatim; anything else (object,\narray, number, bool) is JSON-stringified, mirroring `memory-set`. Read it\nback with `memory-get` (raw) or `memory-get-as` (parsed).",
    )
    providers: ProviderImpls | None = Field(
        {}, description='Named provider implementations.', validate_default=True
    )
    runtime: RuntimeImpls | None = Field(
        {}, description='Named runtime implementations.', validate_default=True
    )
    tooling: ToolingImpls | None = Field(
        {}, description='Named tooling implementations.', validate_default=True
    )
    tunables: Tunables | None = Field(
        {
            'allow_unlocked_secrets': False,
            'cancel_pumps_on_reload': True,
            'inbox_bound': 1024,
            'interrupt_budget_ms': 100,
            'loop_backoff_cap_secs': 30,
            'loop_backoff_start_ms': 100,
            'recv_slice_ms': 200,
            'recv_timeout_secs': 60,
            'reload_grace_secs': 5,
            'reload_poll_ms': 200,
            'session_buffer': 8192,
            'test_timeout_secs': 30,
            'tooling_connect_backoff_cap_secs': 30,
            'tooling_connect_backoff_start_ms': 100,
            'trace_buffer': 4096,
            'tui_tab_capacity': 2000,
            'tui_tick_ms': 80,
            'watch_debounce_ms': 200,
        },
        description='Global runtime tunables.',
        validate_default=True,
    )
