declare namespace OmwTestConfig {
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  /**
   * When a scripted step fires: "start" (the default) or a `call`/`inbound` pattern to wait for.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "After".
   */
  export type After =
    | "start"
    | {
        [k: string]: unknown;
      };
  /**
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Secret".
   */
  export type Secret = string;
  /**
   * Filesystem permissions for one [`Preopen`].
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "FsPerms".
   */
  export type FsPerms = "read_only" | "read_write";
  /**
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "EndpointImpls".
   */
  export type EndpointImpls =
    | (
        | (Config6 & {
            kind: "mock";
            [k: string]: unknown;
          })
        | ImplConfig
      )
    | null;

  /**
   * OMW configuration.
   */
  export interface Config {
    /**
     * Agents that OMW is going to run, keyed by agent name.
     */
    agents?: {
      [k: string]: AgentConfig;
    };
    /**
     * Optional endpoint implementation.
     */
    endpoint?:
      | (
          | (Config6 & {
              kind: "mock";
              [k: string]: unknown;
            })
          | ImplConfig
        )
      | null;
    /**
     * Per-agent seeded memory, keyed by agent name then key. Seeded into the
     * agent's memory before its brain first runs, so a test (or a deployment)
     * can fast-forward an agent to a state. Seeded values persist like any
     * other memory, including across hot reloads.
     *
     * A value that is a string is stored verbatim; anything else (object,
     * array, number, bool) is JSON-stringified, mirroring `memory-set`. Read it
     * back with `memory-get` (raw) or `memory-get-as` (parsed).
     */
    memory?: {
      [k: string]: {
        [k: string]: unknown;
      };
    };
    providers?: ProviderImpls;
    runtime?: RuntimeImpls;
    tooling?: ToolingImpls;
    tunables?: Tunables;
    [k: string]: unknown;
  }
  /**
   * A single agent wiring itself to the globals above. The agent's name is the
   * key it appears under in [`Config::agents`].
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "AgentConfig".
   */
  export interface AgentConfig {
    /**
     * Which named runtime implementation this agent's brain uses.
     */
    runtime: string;
    /**
     * The agent's brain script.
     */
    script: string;
    [k: string]: unknown;
  }
  /**
   * Impl-specific configuration for the endpoint mock.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Config6".
   */
  export interface Config6 {
    /**
     * How long to wait between polls for a model subscription.
     */
    poll_ms?: number;
    requests?: Request[];
    [k: string]: unknown;
  }
  /**
   * One scripted request the mock routes into a subscribed agent.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Request".
   */
  export interface Request {
    /**
     * Ordering gate: absent or `"start"` fires as soon as the model is
     * subscribed; a `call`/`inbound` pattern waits for a matching trace event.
     */
    after?: After | null;
    messages?: InboundMessage[];
    model: string;
    /**
     * Opaque generation params the client submitted (temperature, …).
     */
    params?: {
      [k: string]: unknown;
    };
    /**
     * Whether the client asked for SSE. Informational only; the mock drains
     * the same session either way.
     */
    stream?: boolean;
    tools?: Tool[];
    [k: string]: unknown;
  }
  /**
   * One inbound chat message from the scripted client. Kept local so the mock
   * does not require the provider DTOs to be deserializable.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "InboundMessage".
   */
  export interface InboundMessage {
    content?: string | null;
    reasoning?: string | null;
    role?: string;
    [k: string]: unknown;
  }
  /**
   * A tool exposed by a tooling.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Tool".
   */
  export interface Tool {
    description?: string | null;
    /**
     * JSON Schema for the tool's arguments.
     */
    input_schema: {
      [k: string]: unknown;
    };
    name: string;
    /**
     * Optional JSON Schema for the tool's structured output (MCP
     * `outputSchema`). Absent when the tool declares no output shape.
     */
    output_schema?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }
  /**
   * A single configured implementation: which kind plus opaque params.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "ImplConfig".
   */
  export interface ImplConfig {
    /**
     * Which implementation this is.
     */
    kind: string;
    [k: string]: unknown;
  }
  /**
   * Named provider implementations.
   */
  export interface ProviderImpls {
    [k: string]:
      | (Config1 & {
          kind: "mock";
          [k: string]: unknown;
        })
      | ImplConfig;
  }
  /**
   * Impl-specific configuration for the mock provider.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Config".
   */
  export interface Config1 {
    /**
     * The model names `list-models` returns. Defaults to `["mock-model"]`.
     */
    models?: string[];
    /**
     * Scripted turns; one is popped per `chat` (repeating the last once
     * exhausted).
     */
    turns?: Turn[];
    [k: string]: unknown;
  }
  /**
   * One scripted turn: optional reasoning, content, a tool call, and usage.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Turn".
   */
  export interface Turn {
    /**
     * Plain content emitted before the terminal finish reason.
     */
    content?: string | null;
    /**
     * Reasoning/thinking content emitted as its own delta.
     */
    reasoning?: string | null;
    /**
     * A tool call, which makes the terminal finish reason `"tool_calls"`.
     */
    tool_call?: MockToolCallSpec | null;
    /**
     * Token accounting attached to the terminal delta.
     */
    usage?: UsageSpec | null;
    [k: string]: unknown;
  }
  /**
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "MockToolCallSpec".
   */
  export interface MockToolCallSpec {
    arguments: unknown;
    id: string;
    name: string;
    [k: string]: unknown;
  }
  /**
   * The scripted token counts of one turn.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "UsageSpec".
   */
  export interface UsageSpec {
    completion_tokens?: number | null;
    prompt_tokens?: number | null;
    total_tokens?: number | null;
    [k: string]: unknown;
  }
  /**
   * Named runtime implementations.
   */
  export interface RuntimeImpls {
    [k: string]:
      | (Config3 & {
          kind: "wasm";
          [k: string]: unknown;
        })
      | (Config4 & {
          kind: "rhai";
          [k: string]: unknown;
        })
      | (Config5 & {
          kind: "js";
          [k: string]: unknown;
        })
      | ImplConfig;
  }
  /**
   * WASI context configuration for wasm-based runtimes, flattened into each
   * runtime's own config. Deny-by-default, mirroring
   * `WasiCtxBuilder::default()`: no stdio inheritance, no env, no args, no
   * preopens, no network.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Config3".
   */
  export interface Config3 {
    allow_blocking_current_thread?: boolean;
    allow_ip_name_lookup?: boolean;
    allow_tcp?: boolean;
    allow_udp?: boolean;
    args?: string[];
    env?: {
      [k: string]: Secret;
    };
    inherit_args?: boolean;
    inherit_env?: boolean;
    inherit_network?: boolean;
    inherit_stderr?: boolean;
    inherit_stdin?: boolean;
    inherit_stdio?: boolean;
    inherit_stdout?: boolean;
    initial_cwd?: string | null;
    insecure_random_seed?: number | null;
    max_random_size?: number | null;
    preopens?: Preopen[];
    [k: string]: unknown;
  }
  /**
   * One preopened directory: `host_path` on the host, visible to the guest
   * as `guest_path`.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Preopen".
   */
  export interface Preopen {
    guest_path: string;
    host_path: string;
    perms?: FsPerms;
    [k: string]: unknown;
  }
  /**
   * Impl-specific configuration for the Rhai runtime.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Config4".
   */
  export interface Config4 {
    allow_blocking_current_thread?: boolean;
    allow_ip_name_lookup?: boolean;
    allow_tcp?: boolean;
    allow_udp?: boolean;
    args?: string[];
    env?: {
      [k: string]: Secret;
    };
    inherit_args?: boolean;
    inherit_env?: boolean;
    inherit_network?: boolean;
    inherit_stderr?: boolean;
    inherit_stdin?: boolean;
    inherit_stdio?: boolean;
    inherit_stdout?: boolean;
    initial_cwd?: string | null;
    insecure_random_seed?: number | null;
    interpreter?: string | null;
    max_random_size?: number | null;
    preopens?: Preopen[];
    [k: string]: unknown;
  }
  /**
   * Impl-specific configuration for the js runtime.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Config5".
   */
  export interface Config5 {
    allow_blocking_current_thread?: boolean;
    allow_ip_name_lookup?: boolean;
    allow_tcp?: boolean;
    allow_udp?: boolean;
    args?: string[];
    env?: {
      [k: string]: Secret;
    };
    inherit_args?: boolean;
    inherit_env?: boolean;
    inherit_network?: boolean;
    inherit_stderr?: boolean;
    inherit_stdin?: boolean;
    inherit_stdio?: boolean;
    inherit_stdout?: boolean;
    initial_cwd?: string | null;
    insecure_random_seed?: number | null;
    interpreter?: string | null;
    max_random_size?: number | null;
    preopens?: Preopen[];
    [k: string]: unknown;
  }
  /**
   * Named tooling implementations.
   */
  export interface ToolingImpls {
    [k: string]:
      | (Config2 & {
          kind: "mock";
          [k: string]: unknown;
        })
      | ImplConfig;
  }
  /**
   * Impl-specific configuration for the mock tooling.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Config2".
   */
  export interface Config2 {
    /**
     * How long each scripted step waits before firing.
     */
    delay_ms?: number;
    /**
     * Canned resource content keyed by URI, returned by `read-resource`.
     */
    initial_resource_contents?: {
      [k: string]: string;
    };
    /**
     * The resource list `list-resources` starts from.
     */
    initial_resource_list?: ResourceInfo[];
    /**
     * Ordered, one-by-one content updates driven by `subscribe-resource`.
     */
    resource_content_updates?: ResourceContentUpdate[];
    /**
     * Ordered, full-replacement resource-list updates driven by
     * `subscribe-resource-list`.
     */
    resource_list_updates?: ResourceListUpdate[];
    /**
     * Ordered `call-tool` results; consumed one per call and name-verified.
     */
    tool_calls?: ScriptedToolCall[];
    tools?: Tool[];
    [k: string]: unknown;
  }
  /**
   * An MCP resource (a URI-addressed, readable data value) exposed by a
   * tooling.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "ResourceInfo".
   */
  export interface ResourceInfo {
    description?: string | null;
    mime_type?: string | null;
    name: string;
    uri: string;
    [k: string]: unknown;
  }
  /**
   * One scripted, one-by-one resource-content update.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "ResourceContentUpdate".
   */
  export interface ResourceContentUpdate {
    after?: After;
    content: string;
    uri: string;
    [k: string]: unknown;
  }
  /**
   * One scripted, full-replacement resource-list update.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "ResourceListUpdate".
   */
  export interface ResourceListUpdate {
    after?: After;
    resources: ResourceInfo[];
    [k: string]: unknown;
  }
  /**
   * One scripted `call-tool` result. `result` is a text convenience that
   * becomes a single MCP text content block; `structured_content` is passed
   * through verbatim.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "ScriptedToolCall".
   */
  export interface ScriptedToolCall {
    after?: After;
    name: string;
    result?: string;
    structured_content?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }
  /**
   * Global runtime tunables.
   */
  export interface Tunables {
    /**
     * Permit secrets to stay unlocked (pageable) when `mlock` fails, e.g.
     * inside containers where the outer `RLIMIT_MEMLOCK` cannot be raised.
     * Default `false` (fail-closed). Only enable where the weaker guarantee
     * is acceptable.
     */
    allow_unlocked_secrets?: boolean;
    /**
     * Cancel open pumps (streams, timers, resources, tool calls) on reload.
     * `false` keeps them across reload.
     */
    cancel_pumps_on_reload?: boolean;
    /**
     * How many events a single agent inbox buffers before sends fail.
     */
    inbox_bound?: number;
    /**
     * Uninterrupted runtime execution allowed after grace expires, in ms.
     */
    interrupt_budget_ms?: number;
    /**
     * Backoff cap for `loop` restarts on failure, in seconds.
     */
    loop_backoff_cap_secs?: number;
    /**
     * Backoff start for `loop` restarts on failure, in ms.
     */
    loop_backoff_start_ms?: number;
    /**
     * How long `recv_while` parks between early-abort checks, in ms.
     */
    recv_slice_ms?: number;
    /**
     * How long a blocking `recv` waits before timing out, in seconds.
     */
    recv_timeout_secs?: number;
    /**
     * How long the supervisor waits for a cooperative exit, in seconds.
     */
    reload_grace_secs?: number;
    /**
     * How long the blocking-call helper waits between reload checks, in ms.
     */
    reload_poll_ms?: number;
    /**
     * How many deltas a single endpoint session buffers before drops.
     */
    session_buffer?: number;
    /**
     * How long a single testing-harness run may take before it is force-stopped
     * and every unsettled agent marked timed out, in seconds. `0` disables it.
     */
    test_timeout_secs?: number;
    /**
     * Backoff cap for tooling reconnects on failure, in seconds.
     */
    tooling_connect_backoff_cap_secs?: number;
    /**
     * Backoff start for tooling reconnects on failure, in ms.
     */
    tooling_connect_backoff_start_ms?: number;
    /**
     * How many trace events the `omw-test` broadcast channel buffers.
     */
    trace_buffer?: number;
    /**
     * How many log lines each live-view tab keeps before the oldest are
     * dropped. `0` means unlimited.
     */
    tui_tab_capacity?: number;
    /**
     * How long the live view's render loop waits between redraws, in ms. It is
     * both the spinner cadence and the maximum redraw interval.
     */
    tui_tick_ms?: number;
    /**
     * How long to coalesce the burst of file events a single save produces,
     * in ms.
     */
    watch_debounce_ms?: number;
    [k: string]: unknown;
  }
  /**
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "ProviderImpls".
   */
  export interface ProviderImpls1 {
    [k: string]:
      | (Config1 & {
          kind: "mock";
          [k: string]: unknown;
        })
      | ImplConfig;
  }
  /**
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "RuntimeImpls".
   */
  export interface RuntimeImpls1 {
    [k: string]:
      | (Config3 & {
          kind: "wasm";
          [k: string]: unknown;
        })
      | (Config4 & {
          kind: "rhai";
          [k: string]: unknown;
        })
      | (Config5 & {
          kind: "js";
          [k: string]: unknown;
        })
      | ImplConfig;
  }
  /**
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "ToolingImpls".
   */
  export interface ToolingImpls1 {
    [k: string]:
      | (Config2 & {
          kind: "mock";
          [k: string]: unknown;
        })
      | ImplConfig;
  }
  /**
   * Runtime tunables: channel sizes, timeouts, and backoffs. All optional;
   * omitted values fall back to the built-in defaults.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Tunables".
   */
  export interface Tunables1 {
    /**
     * Permit secrets to stay unlocked (pageable) when `mlock` fails, e.g.
     * inside containers where the outer `RLIMIT_MEMLOCK` cannot be raised.
     * Default `false` (fail-closed). Only enable where the weaker guarantee
     * is acceptable.
     */
    allow_unlocked_secrets?: boolean;
    /**
     * Cancel open pumps (streams, timers, resources, tool calls) on reload.
     * `false` keeps them across reload.
     */
    cancel_pumps_on_reload?: boolean;
    /**
     * How many events a single agent inbox buffers before sends fail.
     */
    inbox_bound?: number;
    /**
     * Uninterrupted runtime execution allowed after grace expires, in ms.
     */
    interrupt_budget_ms?: number;
    /**
     * Backoff cap for `loop` restarts on failure, in seconds.
     */
    loop_backoff_cap_secs?: number;
    /**
     * Backoff start for `loop` restarts on failure, in ms.
     */
    loop_backoff_start_ms?: number;
    /**
     * How long `recv_while` parks between early-abort checks, in ms.
     */
    recv_slice_ms?: number;
    /**
     * How long a blocking `recv` waits before timing out, in seconds.
     */
    recv_timeout_secs?: number;
    /**
     * How long the supervisor waits for a cooperative exit, in seconds.
     */
    reload_grace_secs?: number;
    /**
     * How long the blocking-call helper waits between reload checks, in ms.
     */
    reload_poll_ms?: number;
    /**
     * How many deltas a single endpoint session buffers before drops.
     */
    session_buffer?: number;
    /**
     * How long a single testing-harness run may take before it is force-stopped
     * and every unsettled agent marked timed out, in seconds. `0` disables it.
     */
    test_timeout_secs?: number;
    /**
     * Backoff cap for tooling reconnects on failure, in seconds.
     */
    tooling_connect_backoff_cap_secs?: number;
    /**
     * Backoff start for tooling reconnects on failure, in ms.
     */
    tooling_connect_backoff_start_ms?: number;
    /**
     * How many trace events the `omw-test` broadcast channel buffers.
     */
    trace_buffer?: number;
    /**
     * How many log lines each live-view tab keeps before the oldest are
     * dropped. `0` means unlimited.
     */
    tui_tab_capacity?: number;
    /**
     * How long the live view's render loop waits between redraws, in ms. It is
     * both the spinner cadence and the maximum redraw interval.
     */
    tui_tick_ms?: number;
    /**
     * How long to coalesce the burst of file events a single save produces,
     * in ms.
     */
    watch_debounce_ms?: number;
    [k: string]: unknown;
  }
}
