// The WASM component export ABI generated by `export!` necessarily uses
// `unsafe` (`#[unsafe(export_name)]` shims), so `unsafe_code` cannot be denied
// in this crate.
#![deny(
  clippy::unwrap_used,
  clippy::expect_used,
  clippy::panic,
  clippy::unreachable
)]
#![deny(clippy::arithmetic_side_effects)]
#![deny(clippy::todo)]
#![deny(clippy::allow_attributes_without_reason)]
#![no_main]

//! The bundled rhai evaluator component.
//!
//! Compiles to `wasm32-wasip2` and exports `omw:omw/runtime`: `run(script)`
//! evaluates the agent's `.rhai` script. Inside a script, the `omw.provider`,
//! `omw.tooling` and `omw.host` tables are provided by the modules built in
//! `install_omw`; each call routes to the host through the generated imports.
//!
//! Provider/tooling instances are looked up by name with `get`, which returns
//! an object map holding the configured name plus function pointers for its
//! methods, so scripts can call them method-style (`p.chat(...)`,
//! `t.call_tool(...)`).

wit_bindgen::generate!({
    world: "omw",
    path: "wit",
});

mod convert;
mod host;
mod provider;
mod tooling;

use rhai_rt::{Dynamic, Engine, Module};

use crate::exports::omw::omw::runtime::Guest;
use host::*;
use provider::*;
use tooling::*;

/// Our exported world implementation.
struct Component;

impl Guest for Component {
  fn kind() -> String {
    "rhai".to_string()
  }

  fn run(script: String) -> Result<Option<String>, String> {
    eval_rhai(&script)
  }

  fn check(script: String) -> Result<(), String> {
    let mut engine = Engine::new();
    install_omw(&mut engine);
    engine
      .compile(&script)
      .map(|_| ())
      .map_err(|e| e.to_string())
  }
}

export!(Component);

fn eval_rhai(script: &str) -> Result<Option<String>, String> {
  let mut engine = Engine::new();
  install_omw(&mut engine);

  let result: Dynamic = engine.eval(script).map_err(|e| e.to_string())?;
  if result.is_unit() {
    Ok(None)
  } else {
    Ok(Some(result.to_string()))
  }
}

/// Register the `omw` static module and its `provider`/`tooling`/`host`
/// sub-modules with the engine, plus the handle method implementations.
fn install_omw(engine: &mut Engine) {
  engine.register_fn("provider_chat", provider_chat);
  engine.register_fn("provider_chat_stream", provider_chat_stream);
  engine.register_fn("provider_is_open", provider_is_open);
  engine.register_fn("provider_cancel", provider_cancel);
  engine.register_fn("provider_list_models", provider_list_models);
  engine.register_fn("provider_kind", provider_kind);
  engine.register_fn("tooling_list_tools", tooling_list_tools);
  engine.register_fn("tooling_call_tool", tooling_call_tool);
  engine.register_fn("tooling_call_tool_blocking", tooling_call_tool_blocking);
  engine.register_fn("tooling_is_open", tooling_is_open);
  engine.register_fn("tooling_cancel", tooling_cancel);
  engine.register_fn("tooling_kind", tooling_kind);
  engine.register_fn("tooling_list_resources", tooling_list_resources);
  engine.register_fn("tooling_read_resource", tooling_read_resource);
  engine.register_fn(
    "tooling_subscribe_resource_list",
    tooling_subscribe_resource_list,
  );
  engine.register_fn("tooling_subscribe_resource", tooling_subscribe_resource);
  engine.register_fn(
    "tooling_unsubscribe_resource_list",
    tooling_unsubscribe_resource_list,
  );
  engine
    .register_fn("tooling_unsubscribe_resource", tooling_unsubscribe_resource);

  let mut provider = Module::new();
  provider.set_native_fn("get", provider_get);

  let mut tooling = Module::new();
  tooling.set_native_fn("get", tooling_get);

  let mut host = Module::new();
  host.set_native_fn("log", host_log);
  host.set_native_fn("time_now", host_time_now);
  host.set_native_fn("time_format", host_time_format);
  host.set_native_fn("wait_until", host_wait_until);
  host.set_native_fn("wait_for", host_wait_for);
  host.set_native_fn("wait_cron", host_wait_cron);
  host.set_native_fn("sleep_for", host_sleep_for);
  host.set_native_fn("sleep_until", host_sleep_until);
  host.set_native_fn("sleep_cron", host_sleep_cron);
  host.set_native_fn("cancel_timer", host_cancel_timer);
  host.set_native_fn("subscribe_agent", host_subscribe_agent);
  host.set_native_fn("unsubscribe_agent", host_unsubscribe_agent);
  host.set_native_fn("subscribe_lifecycle", host_subscribe_lifecycle);
  host.set_native_fn("unsubscribe_lifecycle", host_unsubscribe_lifecycle);
  host.set_native_fn("send_agent", host_send_agent);
  host.set_native_fn("recv", host_recv);
  host.set_native_fn("try_recv", host_try_recv);
  host.set_native_fn("new_uuid", host_new_uuid);
  host.set_native_fn("base64_encode", host_base64_encode);
  host.set_native_fn("base64_decode", host_base64_decode);
  host.set_native_fn("memory_get", host_memory_get);
  host.set_native_fn("memory_set", host_memory_set);
  host.set_native_fn("memory_remove", host_memory_remove);

  host.set_native_fn("subscribe_endpoint", host_subscribe_endpoint);
  host.set_native_fn("unsubscribe_endpoint", host_unsubscribe_endpoint);
  host.set_native_fn("stream_endpoint", host_stream_endpoint);
  let mut omw = Module::new();
  omw.set_sub_module("provider", provider);
  omw.set_sub_module("tooling", tooling);
  omw.set_sub_module("host", host);
  engine.register_static_module("omw", omw.into());
}
