declare namespace OmwConfig {
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  /**
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Secret".
   */
  export type Secret = string;
  /**
   * Filesystem permissions for one [`Preopen`].
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "FsPerms".
   */
  export type FsPerms = "read_only" | "read_write";
  /**
   * Impl-specific configuration for a single MCP server, selected by
   * transport.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Config2".
   */
  export type Config2 =
    | {
        args?: string[];
        command: string;
        env?: {
          [k: string]: Secret;
        };
        transport: "stdio";
        [k: string]: unknown;
      }
    | {
        auth_token?: Secret | null;
        transport: "http";
        url: string;
        [k: string]: unknown;
      };
  /**
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "EndpointImpls".
   */
  export type EndpointImpls =
    | (
        | (Config4 & {
            kind: "openai";
            [k: string]: unknown;
          })
        | ImplConfig
      )
    | null;

  /**
   * OMW configuration.
   */
  export interface Config {
    /**
     * Agents that OMW is going to run, keyed by agent name.
     */
    agents?: {
      [k: string]: AgentConfig;
    };
    /**
     * Optional endpoint implementation.
     */
    endpoint?:
      | (
          | (Config4 & {
              kind: "openai";
              [k: string]: unknown;
            })
          | ImplConfig
        )
      | null;
    /**
     * Per-agent seeded memory, keyed by agent name then key. Seeded into the
     * agent's memory before its brain first runs, so a test (or a deployment)
     * can fast-forward an agent to a state. Seeded values persist like any
     * other memory, including across hot reloads.
     *
     * A value that is a string is stored verbatim; anything else (object,
     * array, number, bool) is JSON-stringified, mirroring `memory-set`. Read it
     * back with `memory-get` (raw) or `memory-get-as` (parsed).
     */
    memory?: {
      [k: string]: {
        [k: string]: unknown;
      };
    };
    providers?: ProviderImpls;
    runtime?: RuntimeImpls;
    tooling?: ToolingImpls;
    tunables?: Tunables;
    [k: string]: unknown;
  }
  /**
   * A single agent wiring itself to the globals above. The agent's name is the
   * key it appears under in [`Config::agents`].
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "AgentConfig".
   */
  export interface AgentConfig {
    /**
     * Which named runtime implementation this agent's brain uses.
     */
    runtime: string;
    /**
     * The agent's brain script.
     */
    script: string;
    [k: string]: unknown;
  }
  /**
   * Impl-specific configuration for the OpenAI-compatible endpoint.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Config4".
   */
  export interface Config4 {
    /**
     * Socket address to listen on, e.g. `"127.0.0.1:37532"` or
     * `"0.0.0.0:37532"`. Hostnames (e.g. `"localhost:37532"`) are rejected at
     * startup.
     */
    listen: string;
    [k: string]: unknown;
  }
  /**
   * A single configured implementation: which kind plus opaque params.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "ImplConfig".
   */
  export interface ImplConfig {
    /**
     * Which implementation this is.
     */
    kind: string;
    [k: string]: unknown;
  }
  /**
   * Named provider implementations.
   */
  export interface ProviderImpls {
    [k: string]:
      | (Config1 & {
          kind: "openai";
          [k: string]: unknown;
        })
      | ImplConfig;
  }
  /**
   * Impl-specific configuration for the OpenAI-family provider.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Config".
   */
  export interface Config1 {
    api_key?: Secret | null;
    base_url?: string | null;
    model?: string | null;
    /**
     * Default generation params merged into every request body (temperature,
     * max_tokens, reasoning_effort, …). Per-call params override these.
     */
    params?: {
      [k: string]: unknown;
    } | null;
    [k: string]: unknown;
  }
  /**
   * Named runtime implementations.
   */
  export interface RuntimeImpls {
    [k: string]:
      | (Config3 & {
          kind: "wasm";
          [k: string]: unknown;
        })
      | ImplConfig;
  }
  /**
   * WASI context configuration for wasm-based runtimes, flattened into each
   * runtime's own config. Deny-by-default, mirroring
   * `WasiCtxBuilder::default()`: no stdio inheritance, no env, no args, no
   * preopens, no network.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Config3".
   */
  export interface Config3 {
    allow_blocking_current_thread?: boolean;
    allow_ip_name_lookup?: boolean;
    allow_tcp?: boolean;
    allow_udp?: boolean;
    args?: string[];
    env?: {
      [k: string]: Secret;
    };
    inherit_args?: boolean;
    inherit_env?: boolean;
    inherit_network?: boolean;
    inherit_stderr?: boolean;
    inherit_stdin?: boolean;
    inherit_stdio?: boolean;
    inherit_stdout?: boolean;
    initial_cwd?: string | null;
    insecure_random_seed?: number | null;
    max_random_size?: number | null;
    preopens?: Preopen[];
    [k: string]: unknown;
  }
  /**
   * One preopened directory: `host_path` on the host, visible to the guest
   * as `guest_path`.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Preopen".
   */
  export interface Preopen {
    guest_path: string;
    host_path: string;
    perms?: FsPerms;
    [k: string]: unknown;
  }
  /**
   * Named tooling implementations.
   */
  export interface ToolingImpls {
    [k: string]:
      | (Config2 & {
          kind: "mcp";
          [k: string]: unknown;
        })
      | ImplConfig;
  }
  /**
   * Global runtime tunables.
   */
  export interface Tunables {
    /**
     * Permit secrets to stay unlocked (pageable) when `mlock` fails, e.g.
     * inside containers where the outer `RLIMIT_MEMLOCK` cannot be raised.
     * Default `false` (fail-closed). Only enable where the weaker guarantee
     * is acceptable.
     */
    allow_unlocked_secrets?: boolean;
    /**
     * Cancel open pumps (streams, timers, resources, tool calls) on reload.
     * `false` keeps them across reload.
     */
    cancel_pumps_on_reload?: boolean;
    /**
     * How many events a single agent inbox buffers before sends fail.
     */
    inbox_bound?: number;
    /**
     * Uninterrupted runtime execution allowed after grace expires, in ms.
     */
    interrupt_budget_ms?: number;
    /**
     * Backoff cap for `loop` restarts on failure, in seconds.
     */
    loop_backoff_cap_secs?: number;
    /**
     * Backoff start for `loop` restarts on failure, in ms.
     */
    loop_backoff_start_ms?: number;
    /**
     * How long `recv_while` parks between early-abort checks, in ms.
     */
    recv_slice_ms?: number;
    /**
     * How long a blocking `recv` waits before timing out, in seconds.
     */
    recv_timeout_secs?: number;
    /**
     * How long the supervisor waits for a cooperative exit, in seconds.
     */
    reload_grace_secs?: number;
    /**
     * How long the blocking-call helper waits between reload checks, in ms.
     */
    reload_poll_ms?: number;
    /**
     * How many deltas a single endpoint session buffers before drops.
     */
    session_buffer?: number;
    /**
     * How long a single testing-harness run may take before it is force-stopped
     * and every unsettled agent marked timed out, in seconds. `0` disables it.
     */
    test_timeout_secs?: number;
    /**
     * Backoff cap for tooling reconnects on failure, in seconds.
     */
    tooling_connect_backoff_cap_secs?: number;
    /**
     * Backoff start for tooling reconnects on failure, in ms.
     */
    tooling_connect_backoff_start_ms?: number;
    /**
     * How many trace events the `omw-test` broadcast channel buffers.
     */
    trace_buffer?: number;
    /**
     * How many log lines each live-view tab keeps before the oldest are
     * dropped. `0` means unlimited.
     */
    tui_tab_capacity?: number;
    /**
     * How long the live view's render loop waits between redraws, in ms. It is
     * both the spinner cadence and the maximum redraw interval.
     */
    tui_tick_ms?: number;
    /**
     * How long to coalesce the burst of file events a single save produces,
     * in ms.
     */
    watch_debounce_ms?: number;
    [k: string]: unknown;
  }
  /**
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "ProviderImpls".
   */
  export interface ProviderImpls1 {
    [k: string]:
      | (Config1 & {
          kind: "openai";
          [k: string]: unknown;
        })
      | ImplConfig;
  }
  /**
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "RuntimeImpls".
   */
  export interface RuntimeImpls1 {
    [k: string]:
      | (Config3 & {
          kind: "wasm";
          [k: string]: unknown;
        })
      | ImplConfig;
  }
  /**
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "ToolingImpls".
   */
  export interface ToolingImpls1 {
    [k: string]:
      | (Config2 & {
          kind: "mcp";
          [k: string]: unknown;
        })
      | ImplConfig;
  }
  /**
   * Runtime tunables: channel sizes, timeouts, and backoffs. All optional;
   * omitted values fall back to the built-in defaults.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Tunables".
   */
  export interface Tunables1 {
    /**
     * Permit secrets to stay unlocked (pageable) when `mlock` fails, e.g.
     * inside containers where the outer `RLIMIT_MEMLOCK` cannot be raised.
     * Default `false` (fail-closed). Only enable where the weaker guarantee
     * is acceptable.
     */
    allow_unlocked_secrets?: boolean;
    /**
     * Cancel open pumps (streams, timers, resources, tool calls) on reload.
     * `false` keeps them across reload.
     */
    cancel_pumps_on_reload?: boolean;
    /**
     * How many events a single agent inbox buffers before sends fail.
     */
    inbox_bound?: number;
    /**
     * Uninterrupted runtime execution allowed after grace expires, in ms.
     */
    interrupt_budget_ms?: number;
    /**
     * Backoff cap for `loop` restarts on failure, in seconds.
     */
    loop_backoff_cap_secs?: number;
    /**
     * Backoff start for `loop` restarts on failure, in ms.
     */
    loop_backoff_start_ms?: number;
    /**
     * How long `recv_while` parks between early-abort checks, in ms.
     */
    recv_slice_ms?: number;
    /**
     * How long a blocking `recv` waits before timing out, in seconds.
     */
    recv_timeout_secs?: number;
    /**
     * How long the supervisor waits for a cooperative exit, in seconds.
     */
    reload_grace_secs?: number;
    /**
     * How long the blocking-call helper waits between reload checks, in ms.
     */
    reload_poll_ms?: number;
    /**
     * How many deltas a single endpoint session buffers before drops.
     */
    session_buffer?: number;
    /**
     * How long a single testing-harness run may take before it is force-stopped
     * and every unsettled agent marked timed out, in seconds. `0` disables it.
     */
    test_timeout_secs?: number;
    /**
     * Backoff cap for tooling reconnects on failure, in seconds.
     */
    tooling_connect_backoff_cap_secs?: number;
    /**
     * Backoff start for tooling reconnects on failure, in ms.
     */
    tooling_connect_backoff_start_ms?: number;
    /**
     * How many trace events the `omw-test` broadcast channel buffers.
     */
    trace_buffer?: number;
    /**
     * How many log lines each live-view tab keeps before the oldest are
     * dropped. `0` means unlimited.
     */
    tui_tab_capacity?: number;
    /**
     * How long the live view's render loop waits between redraws, in ms. It is
     * both the spinner cadence and the maximum redraw interval.
     */
    tui_tick_ms?: number;
    /**
     * How long to coalesce the burst of file events a single save produces,
     * in ms.
     */
    watch_debounce_ms?: number;
    [k: string]: unknown;
  }
}

declare namespace OmwTestConfig {
  /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

  /**
   * When a scripted step fires: "start" (the default) or a `call`/`inbound` pattern to wait for.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "After".
   */
  export type After =
    | "start"
    | {
        [k: string]: unknown;
      };
  /**
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Secret".
   */
  export type Secret = string;
  /**
   * Filesystem permissions for one [`Preopen`].
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "FsPerms".
   */
  export type FsPerms = "read_only" | "read_write";
  /**
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "EndpointImpls".
   */
  export type EndpointImpls =
    | (
        | (Config6 & {
            kind: "mock";
            [k: string]: unknown;
          })
        | ImplConfig
      )
    | null;

  /**
   * OMW configuration.
   */
  export interface Config {
    /**
     * Agents that OMW is going to run, keyed by agent name.
     */
    agents?: {
      [k: string]: AgentConfig;
    };
    /**
     * Optional endpoint implementation.
     */
    endpoint?:
      | (
          | (Config6 & {
              kind: "mock";
              [k: string]: unknown;
            })
          | ImplConfig
        )
      | null;
    /**
     * Per-agent seeded memory, keyed by agent name then key. Seeded into the
     * agent's memory before its brain first runs, so a test (or a deployment)
     * can fast-forward an agent to a state. Seeded values persist like any
     * other memory, including across hot reloads.
     *
     * A value that is a string is stored verbatim; anything else (object,
     * array, number, bool) is JSON-stringified, mirroring `memory-set`. Read it
     * back with `memory-get` (raw) or `memory-get-as` (parsed).
     */
    memory?: {
      [k: string]: {
        [k: string]: unknown;
      };
    };
    providers?: ProviderImpls;
    runtime?: RuntimeImpls;
    tooling?: ToolingImpls;
    tunables?: Tunables;
    [k: string]: unknown;
  }
  /**
   * A single agent wiring itself to the globals above. The agent's name is the
   * key it appears under in [`Config::agents`].
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "AgentConfig".
   */
  export interface AgentConfig {
    /**
     * Which named runtime implementation this agent's brain uses.
     */
    runtime: string;
    /**
     * The agent's brain script.
     */
    script: string;
    [k: string]: unknown;
  }
  /**
   * Impl-specific configuration for the endpoint mock.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Config6".
   */
  export interface Config6 {
    requests?: Request[];
    [k: string]: unknown;
  }
  /**
   * One scripted request the mock routes into a subscribed agent.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Request".
   */
  export interface Request {
    /**
     * Ordering gate: absent or `"start"` fires as soon as the model is
     * subscribed; a `call`/`inbound` pattern waits for a matching trace event.
     */
    after?: After | null;
    messages?: InboundMessage[];
    model: string;
    /**
     * Opaque generation params the client submitted (temperature, …).
     */
    params?: {
      [k: string]: unknown;
    };
    /**
     * Opt-in scripted ending: `{ close = N }` ends the session normally after
     * `N` received deltas, `{ abort = N }` aborts it. Absent, the mock drains
     * silently as before.
     */
    session_end?: SessionEnd | null;
    /**
     * A user-written label for the session, so concurrent sessions can be told
     * apart. The mock correlates it with the opaque session UUID the host and
     * brain see and records both in the snapshot; it is never asserted or
     * matched. Reusing a label after its session closed is a new session with a
     * new UUID.
     */
    session_id: string;
    /**
     * Whether the client asked for SSE. Informational only; the mock drains
     * the same session either way.
     */
    stream?: boolean;
    tools?: Tool[];
    [k: string]: unknown;
  }
  /**
   * One inbound chat message from the scripted client. Kept local so the mock
   * does not require the provider DTOs to be deserializable.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "InboundMessage".
   */
  export interface InboundMessage {
    content?: string | null;
    reasoning?: string | null;
    role?: string;
    [k: string]: unknown;
  }
  /**
   * How a scripted request ends its session.
   *
   * `{ close = N }` removes the session and delivers a normal
   * `endpoint-session-end` after `N` received deltas; `{ abort = N }` aborts it
   * with an error instead. `N = 0` fires immediately after routing. If the
   * reply ends first (terminal finish-reason or `Close`) the script is a no-op.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "SessionEnd".
   */
  export interface SessionEnd {
    abort?: number | null;
    close?: number | null;
    [k: string]: unknown;
  }
  /**
   * A tool exposed by a tooling.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Tool".
   */
  export interface Tool {
    description?: string | null;
    /**
     * JSON Schema for the tool's arguments.
     */
    input_schema: {
      [k: string]: unknown;
    };
    name: string;
    /**
     * Optional JSON Schema for the tool's structured output (MCP
     * `outputSchema`). Absent when the tool declares no output shape.
     */
    output_schema?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }
  /**
   * A single configured implementation: which kind plus opaque params.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "ImplConfig".
   */
  export interface ImplConfig {
    /**
     * Which implementation this is.
     */
    kind: string;
    [k: string]: unknown;
  }
  /**
   * Named provider implementations.
   */
  export interface ProviderImpls {
    [k: string]:
      | (Config1 & {
          kind: "mock";
          [k: string]: unknown;
        })
      | ImplConfig;
  }
  /**
   * Impl-specific configuration for the mock provider.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Config".
   */
  export interface Config1 {
    /**
     * The model names `list-models` returns. Defaults to `["mock-model"]`.
     */
    models?: string[];
    /**
     * Scripted turns; one is popped per `chat` (repeating the last once
     * exhausted).
     */
    turns?: Turn[];
    [k: string]: unknown;
  }
  /**
   * One scripted turn: optional reasoning, content, a tool call, usage, and an
   * optional failure or pending marker.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Turn".
   */
  export interface Turn {
    /**
     * Plain content emitted before the terminal finish reason.
     */
    content?: string | null;
    /**
     * Fail the stream with this error, after emitting the turn's deltas.
     */
    error?: string | null;
    /**
     * Never yield: the stream stays pending forever (for cancellation tests).
     */
    pending?: boolean;
    /**
     * Reasoning/thinking content emitted as its own delta.
     */
    reasoning?: string | null;
    /**
     * A tool call, which makes the terminal finish reason `"tool_calls"`.
     */
    tool_call?: MockToolCallSpec | null;
    /**
     * Token accounting attached to the terminal delta.
     */
    usage?: UsageSpec | null;
    [k: string]: unknown;
  }
  /**
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "MockToolCallSpec".
   */
  export interface MockToolCallSpec {
    arguments: unknown;
    id: string;
    name: string;
    [k: string]: unknown;
  }
  /**
   * The scripted token counts of one turn.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "UsageSpec".
   */
  export interface UsageSpec {
    completion_tokens?: number | null;
    prompt_tokens?: number | null;
    total_tokens?: number | null;
    [k: string]: unknown;
  }
  /**
   * Named runtime implementations.
   */
  export interface RuntimeImpls {
    [k: string]:
      | (Config3 & {
          kind: "wasm";
          [k: string]: unknown;
        })
      | (Config4 & {
          kind: "rhai";
          [k: string]: unknown;
        })
      | (Config5 & {
          kind: "js";
          [k: string]: unknown;
        })
      | ImplConfig;
  }
  /**
   * WASI context configuration for wasm-based runtimes, flattened into each
   * runtime's own config. Deny-by-default, mirroring
   * `WasiCtxBuilder::default()`: no stdio inheritance, no env, no args, no
   * preopens, no network.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Config3".
   */
  export interface Config3 {
    allow_blocking_current_thread?: boolean;
    allow_ip_name_lookup?: boolean;
    allow_tcp?: boolean;
    allow_udp?: boolean;
    args?: string[];
    env?: {
      [k: string]: Secret;
    };
    inherit_args?: boolean;
    inherit_env?: boolean;
    inherit_network?: boolean;
    inherit_stderr?: boolean;
    inherit_stdin?: boolean;
    inherit_stdio?: boolean;
    inherit_stdout?: boolean;
    initial_cwd?: string | null;
    insecure_random_seed?: number | null;
    max_random_size?: number | null;
    preopens?: Preopen[];
    [k: string]: unknown;
  }
  /**
   * One preopened directory: `host_path` on the host, visible to the guest
   * as `guest_path`.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Preopen".
   */
  export interface Preopen {
    guest_path: string;
    host_path: string;
    perms?: FsPerms;
    [k: string]: unknown;
  }
  /**
   * Impl-specific configuration for the Rhai runtime.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Config4".
   */
  export interface Config4 {
    allow_blocking_current_thread?: boolean;
    allow_ip_name_lookup?: boolean;
    allow_tcp?: boolean;
    allow_udp?: boolean;
    args?: string[];
    env?: {
      [k: string]: Secret;
    };
    inherit_args?: boolean;
    inherit_env?: boolean;
    inherit_network?: boolean;
    inherit_stderr?: boolean;
    inherit_stdin?: boolean;
    inherit_stdio?: boolean;
    inherit_stdout?: boolean;
    initial_cwd?: string | null;
    insecure_random_seed?: number | null;
    interpreter?: string | null;
    max_random_size?: number | null;
    preopens?: Preopen[];
    [k: string]: unknown;
  }
  /**
   * Impl-specific configuration for the js runtime.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Config5".
   */
  export interface Config5 {
    allow_blocking_current_thread?: boolean;
    allow_ip_name_lookup?: boolean;
    allow_tcp?: boolean;
    allow_udp?: boolean;
    args?: string[];
    env?: {
      [k: string]: Secret;
    };
    inherit_args?: boolean;
    inherit_env?: boolean;
    inherit_network?: boolean;
    inherit_stderr?: boolean;
    inherit_stdin?: boolean;
    inherit_stdio?: boolean;
    inherit_stdout?: boolean;
    initial_cwd?: string | null;
    insecure_random_seed?: number | null;
    interpreter?: string | null;
    max_random_size?: number | null;
    preopens?: Preopen[];
    [k: string]: unknown;
  }
  /**
   * Named tooling implementations.
   */
  export interface ToolingImpls {
    [k: string]:
      | (Config2 & {
          kind: "mock";
          [k: string]: unknown;
        })
      | ImplConfig;
  }
  /**
   * Impl-specific configuration for the mock tooling.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Config2".
   */
  export interface Config2 {
    /**
     * How long each scripted step waits before firing.
     */
    delay_ms?: number;
    /**
     * Canned resource content keyed by URI, returned by `read-resource`.
     */
    initial_resource_contents?: {
      [k: string]: string;
    };
    /**
     * The resource list `list-resources` starts from.
     */
    initial_resource_list?: ResourceInfo[];
    /**
     * Ordered, one-by-one content updates driven by `subscribe-resource`.
     */
    resource_content_updates?: ResourceContentUpdate[];
    /**
     * Ordered, full-replacement resource-list updates driven by
     * `subscribe-resource-list`.
     */
    resource_list_updates?: ResourceListUpdate[];
    /**
     * Ordered `call-tool` results; consumed one per call and name-verified.
     */
    tool_calls?: ScriptedToolCall[];
    tools?: Tool[];
    [k: string]: unknown;
  }
  /**
   * An MCP resource (a URI-addressed, readable data value) exposed by a
   * tooling.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "ResourceInfo".
   */
  export interface ResourceInfo {
    description?: string | null;
    mime_type?: string | null;
    name: string;
    uri: string;
    [k: string]: unknown;
  }
  /**
   * One scripted, one-by-one resource-content update.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "ResourceContentUpdate".
   */
  export interface ResourceContentUpdate {
    after?: After;
    content: string;
    /**
     * Yield this error for the step instead of an `Updated`.
     */
    error?: string | null;
    /**
     * Never yield: the step stays pending forever (for cancellation tests).
     */
    pending?: boolean;
    uri: string;
    [k: string]: unknown;
  }
  /**
   * One scripted, full-replacement resource-list update.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "ResourceListUpdate".
   */
  export interface ResourceListUpdate {
    after?: After;
    /**
     * Yield this error for the step instead of a `ListChanged`.
     */
    error?: string | null;
    /**
     * Never yield: the step stays pending forever (for cancellation tests).
     */
    pending?: boolean;
    resources: ResourceInfo[];
    [k: string]: unknown;
  }
  /**
   * One scripted `call-tool` result. `result` is a text convenience that
   * becomes a single MCP text content block; `structured_content` is passed
   * through verbatim.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "ScriptedToolCall".
   */
  export interface ScriptedToolCall {
    after?: After;
    /**
     * Fail the call with this error (after the gate and delay).
     */
    error?: string | null;
    name: string;
    /**
     * Never complete: the call stays pending forever (for cancellation tests).
     */
    pending?: boolean;
    result?: string;
    structured_content?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }
  /**
   * Global runtime tunables.
   */
  export interface Tunables {
    /**
     * Permit secrets to stay unlocked (pageable) when `mlock` fails, e.g.
     * inside containers where the outer `RLIMIT_MEMLOCK` cannot be raised.
     * Default `false` (fail-closed). Only enable where the weaker guarantee
     * is acceptable.
     */
    allow_unlocked_secrets?: boolean;
    /**
     * Cancel open pumps (streams, timers, resources, tool calls) on reload.
     * `false` keeps them across reload.
     */
    cancel_pumps_on_reload?: boolean;
    /**
     * How many events a single agent inbox buffers before sends fail.
     */
    inbox_bound?: number;
    /**
     * Uninterrupted runtime execution allowed after grace expires, in ms.
     */
    interrupt_budget_ms?: number;
    /**
     * Backoff cap for `loop` restarts on failure, in seconds.
     */
    loop_backoff_cap_secs?: number;
    /**
     * Backoff start for `loop` restarts on failure, in ms.
     */
    loop_backoff_start_ms?: number;
    /**
     * How long `recv_while` parks between early-abort checks, in ms.
     */
    recv_slice_ms?: number;
    /**
     * How long a blocking `recv` waits before timing out, in seconds.
     */
    recv_timeout_secs?: number;
    /**
     * How long the supervisor waits for a cooperative exit, in seconds.
     */
    reload_grace_secs?: number;
    /**
     * How long the blocking-call helper waits between reload checks, in ms.
     */
    reload_poll_ms?: number;
    /**
     * How many deltas a single endpoint session buffers before drops.
     */
    session_buffer?: number;
    /**
     * How long a single testing-harness run may take before it is force-stopped
     * and every unsettled agent marked timed out, in seconds. `0` disables it.
     */
    test_timeout_secs?: number;
    /**
     * Backoff cap for tooling reconnects on failure, in seconds.
     */
    tooling_connect_backoff_cap_secs?: number;
    /**
     * Backoff start for tooling reconnects on failure, in ms.
     */
    tooling_connect_backoff_start_ms?: number;
    /**
     * How many trace events the `omw-test` broadcast channel buffers.
     */
    trace_buffer?: number;
    /**
     * How many log lines each live-view tab keeps before the oldest are
     * dropped. `0` means unlimited.
     */
    tui_tab_capacity?: number;
    /**
     * How long the live view's render loop waits between redraws, in ms. It is
     * both the spinner cadence and the maximum redraw interval.
     */
    tui_tick_ms?: number;
    /**
     * How long to coalesce the burst of file events a single save produces,
     * in ms.
     */
    watch_debounce_ms?: number;
    [k: string]: unknown;
  }
  /**
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "ProviderImpls".
   */
  export interface ProviderImpls1 {
    [k: string]:
      | (Config1 & {
          kind: "mock";
          [k: string]: unknown;
        })
      | ImplConfig;
  }
  /**
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "RuntimeImpls".
   */
  export interface RuntimeImpls1 {
    [k: string]:
      | (Config3 & {
          kind: "wasm";
          [k: string]: unknown;
        })
      | (Config4 & {
          kind: "rhai";
          [k: string]: unknown;
        })
      | (Config5 & {
          kind: "js";
          [k: string]: unknown;
        })
      | ImplConfig;
  }
  /**
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "ToolingImpls".
   */
  export interface ToolingImpls1 {
    [k: string]:
      | (Config2 & {
          kind: "mock";
          [k: string]: unknown;
        })
      | ImplConfig;
  }
  /**
   * Runtime tunables: channel sizes, timeouts, and backoffs. All optional;
   * omitted values fall back to the built-in defaults.
   *
   * This interface was referenced by `Config`'s JSON-Schema
   * via the `definition` "Tunables".
   */
  export interface Tunables1 {
    /**
     * Permit secrets to stay unlocked (pageable) when `mlock` fails, e.g.
     * inside containers where the outer `RLIMIT_MEMLOCK` cannot be raised.
     * Default `false` (fail-closed). Only enable where the weaker guarantee
     * is acceptable.
     */
    allow_unlocked_secrets?: boolean;
    /**
     * Cancel open pumps (streams, timers, resources, tool calls) on reload.
     * `false` keeps them across reload.
     */
    cancel_pumps_on_reload?: boolean;
    /**
     * How many events a single agent inbox buffers before sends fail.
     */
    inbox_bound?: number;
    /**
     * Uninterrupted runtime execution allowed after grace expires, in ms.
     */
    interrupt_budget_ms?: number;
    /**
     * Backoff cap for `loop` restarts on failure, in seconds.
     */
    loop_backoff_cap_secs?: number;
    /**
     * Backoff start for `loop` restarts on failure, in ms.
     */
    loop_backoff_start_ms?: number;
    /**
     * How long `recv_while` parks between early-abort checks, in ms.
     */
    recv_slice_ms?: number;
    /**
     * How long a blocking `recv` waits before timing out, in seconds.
     */
    recv_timeout_secs?: number;
    /**
     * How long the supervisor waits for a cooperative exit, in seconds.
     */
    reload_grace_secs?: number;
    /**
     * How long the blocking-call helper waits between reload checks, in ms.
     */
    reload_poll_ms?: number;
    /**
     * How many deltas a single endpoint session buffers before drops.
     */
    session_buffer?: number;
    /**
     * How long a single testing-harness run may take before it is force-stopped
     * and every unsettled agent marked timed out, in seconds. `0` disables it.
     */
    test_timeout_secs?: number;
    /**
     * Backoff cap for tooling reconnects on failure, in seconds.
     */
    tooling_connect_backoff_cap_secs?: number;
    /**
     * Backoff start for tooling reconnects on failure, in ms.
     */
    tooling_connect_backoff_start_ms?: number;
    /**
     * How many trace events the `omw-test` broadcast channel buffers.
     */
    trace_buffer?: number;
    /**
     * How many log lines each live-view tab keeps before the oldest are
     * dropped. `0` means unlimited.
     */
    tui_tab_capacity?: number;
    /**
     * How long the live view's render loop waits between redraws, in ms. It is
     * both the spinner cadence and the maximum redraw interval.
     */
    tui_tick_ms?: number;
    /**
     * How long to coalesce the burst of file events a single save produces,
     * in ms.
     */
    watch_debounce_ms?: number;
    [k: string]: unknown;
  }
}

// TypeScript declarations for the `omw` global that the bundled
// `omw-wasm-js-interpreter` component injects into every js brain script.
// Reference it from your editor (`/// <reference path="./omw.d.ts" />`) to get
// completion and checking inside `brain.js`. Scripts are evaluated as plain
// scripts, so nothing is imported: `omw` is a global.
//
// This is the hand-written "bindings" declaration. `omw.all.d.ts` is the
// generated concatenation of the deployment/testing config types and this file,
// and is what you should vendor next to a `brain.js`.
//
// See docs/runtime/js.md for the prose reference.

/** A sender role in a chat conversation. */
type Role = "system" | "user" | "assistant" | "tool";

/** A request for the model to invoke one named tool. */
interface ToolCall {
  /** Tool call identifier. */
  id: string;

  /** Tool name. */
  name: string;

  /**
   * Tool arguments, parsed from JSON when possible (otherwise the raw string).
   * Passing it back into `chat`/`chatStream` re-serializes it.
   */
  arguments: unknown;
}

/** A single message in a chat conversation. */
interface ChatMessage {
  /** The sender; defaults to `"user"` when omitted. */
  role?: Role;

  /** Optional text content; absent on messages bearing only a tool call. */
  content?: string;

  /**
   * Optional reasoning/thinking content. Sent back to the provider on
   * assistant messages when present.
   */
  reasoning?: string;

  /** Optional tool call attached to this message. */
  toolCall?: ToolCall;
}

/** Token accounting for one chat response. */
interface Usage {
  /** Tokens in the prompt/request. */
  promptTokens?: number;

  /** Tokens generated in the response. */
  completionTokens?: number;

  /** Total tokens, when the provider reports it. */
  totalTokens?: number;
}

/** One incremental chunk of a streaming chat response. */
interface ChatDelta {
  /** Optional text content produced by this chunk. */
  content?: string;

  /** Optional reasoning/thinking content produced by this chunk. */
  reasoning?: string;

  /** Optional tool call announced by this chunk. */
  toolCall?: ToolCall;

  /** Optional terminal reason the stream stopped (`"stop"`, `"length"`, …). */
  finishReason?: string;

  /** Optional token accounting reported by this chunk. */
  usage?: Usage;
}

/** A callable tool offered to the model, as passed to `chat`/`chatStream`. */
interface ChatTool {
  /** The tool's name. */
  name: string;

  /** Optional human-readable description of what the tool does. */
  description?: string;

  /** The tool's JSON-schema document; defaults to `{}` when omitted. */
  inputSchema?: unknown;

  /** Optional JSON-schema document; absent when omitted. */
  outputSchema?: unknown;
}

/** A tool as returned by `listTools`. */
interface Tool {
  /** The tool's name. */
  name: string;

  /** Optional human-readable description of what the tool does. */
  description?: string;

  /** The tool's JSON-schema document (camelCase alias), parsed from JSON. */
  inputSchema: unknown;

  /** The tool's optional output JSON-schema document, parsed from JSON. */
  outputSchema?: unknown;
}

/** The full result of a blocking `chat` call. */
interface ChatResult {
  /** The concatenated text content; absent if the response was only calls. */
  content?: string;

  /** The concatenated reasoning/thinking content, when produced. */
  reasoning?: string;

  /** The reassembled tool calls the model made, in first-seen order. */
  toolCalls: ToolCall[];

  /** Optional terminal reason the response stopped (`"stop"`, …). */
  finishReason?: string;

  /** Optional token accounting for the response. */
  usage?: Usage;
}

/** The result of a single tool invocation. */
interface ToolResult {
  /** The tool's name. */
  name: string;

  /**
   * The tool's arguments as passed to `callTool`, parsed from JSON when
   * possible (otherwise the raw string).
   */
  arguments: unknown;

  /**
   * The tool's content blocks (MCP `content`), parsed from JSON when possible
   * (otherwise the raw string). A text block is `{ type: "text", text }`.
   */
  content: unknown;

  /**
   * The tool's structured output (MCP `structuredContent`), parsed from JSON
   * when possible; absent when the tool produced none.
   */
  structuredContent?: unknown;
}

/** A tooling resource as returned by `listResources`. */
interface ResourceInfo {
  /** The URI of this resource (e.g. `file:///path/to/file`). */
  uri: string;

  /** The programmatic name of the resource. */
  name: string;

  /** Optional description of what this resource represents. */
  description?: string;

  /** The MIME type of the resource, if known. */
  mimeType?: string;
}

/**
 * The content of a single resource. `content` holds actual text for textual
 * formats and base64-encoded bytes for anything else; match on `mimeType` to
 * tell the two apart.
 */
interface ResourceContent {
  /** The URI of the resource the content belongs to. */
  uri: string;

  /** The MIME type of the resource, if known. */
  mimeType?: string;

  /** The resource's content: plain text, or base64 for binary formats. */
  content: string;
}

/** An inbound endpoint chat request routed to a subscribed agent. */
interface EndpointMessage {
  /** UUID of the session; deltas streamed back address this. */
  session: string;

  /** The chat history as submitted by the endpoint client. */
  messages: ChatMessage[];

  /** The tools advertised by the endpoint client. */
  tools: ChatTool[];

  /**
   * The generation params the endpoint client submitted (temperature, …),
   * parsed from JSON when possible (otherwise the raw string). Absent when
   * none.
   */
  params?: unknown;
}

/** An endpoint session ended, normally or abruptly. */
interface EndpointSessionEnd {
  /** UUID of the session that ended. */
  session: string;

  /** Present when the session ended abruptly rather than via a reason. */
  error?: string;
}

/** An event delivered to the agent's inbox, tagged with its source UUID. */
type OmwEvent =
  | { id: string; kind: "message"; payload: string }
  | { id: string; kind: "error"; payload: string }
  | { id: string; kind: "timer"; payload: null }
  | { id: string; kind: "reload"; payload: null }
  | { id: string; kind: "shutdown"; payload: null }
  | { id: string; kind: "chat-delta"; payload: ChatDelta }
  | { id: string; kind: "chat-end"; payload: null }
  | { id: string; kind: "tool-result"; payload: ToolResult }
  | { id: string; kind: "resource-list-updated"; payload: ResourceInfo[] }
  | { id: string; kind: "resource-updated"; payload: ResourceContent }
  | { id: string; kind: "endpoint-message"; payload: EndpointMessage }
  | { id: string; kind: "endpoint-session-end"; payload: EndpointSessionEnd };

/** The `kind` string an implementation's config declares, or `string`. */
type KindOf<Impl> = Impl extends { kind: infer K extends string } ? K : string;

/** The configured `params` of an implementation, or an open object/string. */
type ParamsOf<Impl> = Impl extends { params: infer P } ? P : object | string;

/** The named providers of a config, or an open map. */
type ProvidersOf<Config> = Config extends { providers: infer Providers }
  ? Providers
  : Record<string, unknown>;

/** The named tooling of a config, or an open map. */
type ToolingOf<Config> = Config extends { tooling: infer Tooling }
  ? Tooling
  : Record<string, unknown>;

/**
 * A configured provider instance, returned by `omw.provider.get`. Parameterized
 * over the config entry that declared it so `kind()` and `params` stay precise
 * when you instantiate `Omw` with a config type.
 */
interface ProviderHandle<Impl = unknown> {
  /** The configured name of this instance. */
  name: string;

  /** Which implementation this is. */
  kind(): KindOf<Impl>;

  /** Model names this provider exposes. */
  listModels(): string[];

  /**
   * Run a chat conversation to completion and return the full result in-band.
   * Unlike `chatStream`, no events are delivered and the call cannot be
   * cancelled. `params` is an optional object (or JSON string) of generation
   * settings (temperature, max_tokens, reasoning_effort, …) merged over the
   * provider's configured defaults.
   */
  chat(
    model: string,
    messages: ChatMessage[],
    tools: ChatTool[],
    params?: ParamsOf<Impl>,
  ): ChatResult;

  /**
   * Open a streaming chat response. Returns a UUID handle; deltas flow into the
   * inbox as `"chat-delta"` events until a terminal `"chat-end"` (or `"error"`)
   * closes the stream. `params` is as in `chat`.
   */
  chatStream(
    model: string,
    messages: ChatMessage[],
    tools: ChatTool[],
    params?: ParamsOf<Impl>,
  ): string;

  /** Whether a chat stream is still open. */
  isOpen(uuid: string): boolean;

  /** Cancel an open stream by UUID. */
  cancel(uuid: string): void;
}

/**
 * A configured tooling instance, returned by `omw.tooling.get`. Parameterized
 * over the config entry that declared it so `kind()` stays precise when you
 * instantiate `Omw` with a config type.
 */
interface ToolingHandle<Impl = unknown> {
  /** The configured name of this instance. */
  name: string;

  /** Which implementation this is. */
  kind(): KindOf<Impl>;

  /** Every tool this tooling exposes, callable via `callTool`. */
  listTools(): Tool[];

  /**
   * Invoke a tool by name with JSON-serializable arguments; queues the call and
   * returns a UUID handle. The result arrives as a `"tool-result"` event tagged
   * with that UUID (or an `"error"` event on failure).
   */
  callTool(tool: string, args: unknown): string;

  /** Whether a queued tool call is still open. */
  isOpen(uuid: string): boolean;

  /** Cancel a queued tool call by UUID. */
  cancel(uuid: string): void;

  /** Invoke a tool, blocking until the result is ready. */
  callToolBlocking(tool: string, args: unknown): ToolResult;

  /** Enumerate every resource this tooling exposes. */
  listResources(): ResourceInfo[];

  /** Read one resource's current content. */
  readResource(uri: string): ResourceContent;

  /** Subscribe to the resource list changing; returns a UUID handle. */
  subscribeResourceList(): string;

  /** Cancel a resource-list subscription by UUID. */
  unsubscribeResourceList(uuid: string): void;

  /** Subscribe to one resource's updates; returns a UUID handle. */
  subscribeResource(uri: string): string;

  /** Cancel a single-resource subscription by UUID. */
  unsubscribeResource(uuid: string): void;
}

/** The static host helpers, baked into the runtime. */
interface Host {
  /** Write a structured log line; unknown levels default to `"info"`. */
  log(
    level: "trace" | "debug" | "info" | "warn" | "error",
    message: string,
  ): void;

  /** The calling agent's configured name. */
  whoami(): string;

  /** Current wall clock as ticks (milliseconds since the Unix epoch). */
  timeNow(): number;

  /** Format a tick with a strftime-style format string. */
  timeFormat(ts: number, format: string): string;

  /** Wait until a future timestamp; errors if `ts` is not in the future. */
  waitUntil(ts: number): string;

  /** Wait for `ms` milliseconds; returns a UUID handle. */
  waitFor(ms: number): string;

  /** Wait until the next fire of a cron spec; returns a UUID handle. */
  waitCron(spec: string): string;

  /** Blocking wait for `ms` milliseconds (no `"timer"` event). */
  sleepFor(ms: number): void;

  /** Blocking wait until a future timestamp (no `"timer"` event). */
  sleepUntil(ts: number): void;

  /** Blocking wait until the next fire of a cron spec (no `"timer"` event). */
  sleepCron(spec: string): void;

  /** Cancel a pending wait by the UUID its `wait*` call returned. */
  cancelTimer(uuid: string): void;

  /** Subscribe to messages from another agent; returns a UUID handle. */
  subscribeAgent(agent: string): string;

  /** Unsubscribe from another agent's messages by UUID. */
  unsubscribeAgent(uuid: string): void;

  /** Subscribe to lifecycle events; returns a UUID handle (one per run). */
  subscribeLifecycle(): string;

  /** Drop the lifecycle subscription; a foreign UUID is a no-op. */
  unsubscribeLifecycle(uuid: string): void;

  /** Send text to another agent. */
  sendAgent(agent: string, payload: string): void;

  /** Blocking receive of the next event from this agent's inbox. */
  recv(): OmwEvent;

  /** Non-blocking poll of the next event; `undefined` when the inbox is empty. */
  tryRecv(): OmwEvent | undefined;

  /** A fresh v4 UUID string. */
  newUuid(): string;

  /** Encode raw bytes as standard padded base64. */
  base64Encode(bytes: number[]): string;

  /** Decode standard padded base64 back to raw bytes; errors on bad input. */
  base64Decode(data: string): number[];

  /** Read a memory value by key; `undefined` when absent. */
  memoryGet(key: string): string | undefined;

  /**
   * Read a memory value by key, parsing it as JSON when possible. `undefined`
   * when absent; otherwise the parsed object/array/scalar, or the raw string
   * when the stored value is not JSON.
   */
  memoryGetAs(key: string): unknown;

  /** Store a memory value under a key, overwriting. */
  memorySet(key: string, value: string): void;

  /**
   * Store a JSON-serializable value under a key, overwriting. Strings are
   * JSON-encoded, so `memoryGetAs` round-trips. Errors on `undefined`.
   */
  memorySetAs(key: string, value: unknown): void;

  /** Delete a memory value by key; `true` when a value was present. */
  memoryRemove(key: string): boolean;

  /** Subscribe this agent to the endpoint under a model name. */
  subscribeEndpoint(model: string): string;

  /** Drop an endpoint model subscription by UUID. */
  unsubscribeEndpoint(uuid: string): void;

  /** Stream one `chat-delta` to an endpoint session. */
  streamEndpoint(session: string, delta: ChatDelta): void;
}

/**
 * The shape `Omw` needs from a config to constrain lookups. The default `Omw`
 * is instantiated with this, so untyped scripts accept any name.
 */
interface AnyConfig {
  providers: Record<string, unknown>;
  tooling: Record<string, unknown>;
  runtime: Record<string, unknown>;
  endpoint: unknown;
}

/**
 * The `omw` global. Instantiate it with your config type to constrain the names
 * accepted by `provider.get`/`tooling.get` and to carry each entry's `kind`:
 *
 * ```js
 * import config from "./omw.test.json";
 * const typed = omw as Omw<typeof config>;
 * typed.provider.get("openai"); // only configured providers type-check
 * ```
 */
interface Omw<Config = AnyConfig> {
  /** Look up configured provider instances by name. */
  provider: {
    get<Name extends keyof ProvidersOf<Config> & string>(
      name: Name,
    ): ProviderHandle<ProvidersOf<Config>[Name]>;
  };

  /** Look up configured tooling instances by name. */
  tooling: {
    get<Name extends keyof ToolingOf<Config> & string>(
      name: Name,
    ): ToolingHandle<ToolingOf<Config>[Name]>;
  };

  /** The static host helpers. */
  host: Host;
}

declare const omw: Omw;
