[package]
name = "omw-runtime-rhai"
version = "0.1.7"
description = "The bundled rhai interpreter component for the omw agent runtime"
repository.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true

[build-dependencies]
omw-build = { version = "0.1.7", path = "../omw-build" }
