// The WASM component export ABI generated by `export!` necessarily uses
// `unsafe` (`#[unsafe(export_name)]` shims), so `unsafe_code` cannot be denied
// in this crate.
#![deny(
  clippy::unwrap_used,
  clippy::expect_used,
  clippy::panic,
  clippy::unreachable
)]
#![deny(clippy::arithmetic_side_effects)]
#![deny(clippy::todo)]
#![deny(clippy::allow_attributes_without_reason)]
#![no_main]

//! The bundled JS evaluator component.
//!
//! Compiles to `wasm32-wasip2` and exports `omw:omw/runtime`: `run(script)`
//! evaluates the agent's `.js` script. Inside a script, the `omw` global holds
//! three namespaces mirroring the rhai interpreter's `omw` module: `provider`
//! / `tooling` / `host`.
//!
//! Provider/tooling instances are looked up by name with `get`, which returns
//! an object holding the configured name plus its methods, so scripts call
//! them method-style (`p.chat(...)`, `t.callTool(...)`), camelCase only.

wit_bindgen::generate!({
    world: "omw",
    path: "wit",
});

mod convert;
mod host;
mod provider;
mod tooling;

use boa_engine::{Context, JsError, JsValue, Source};

/// Our exported world implementation.
struct Component;

impl crate::exports::omw::omw::runtime::Guest for Component {
  fn kind() -> String {
    "js".to_string()
  }

  fn run(script: String) -> Result<Option<String>, String> {
    eval_js(&script).map_err(|e| e.to_string())
  }

  fn check(script: String) -> Result<(), String> {
    parse_js(&script).map_err(|e| e.to_string())
  }
}

export!(Component);

fn install_ctx(ctx: &mut Context) -> Result<(), JsError> {
  use boa_engine::{NativeFunction, js_string};
  let omw = boa_engine::object::ObjectInitializer::new(ctx).build();
  let provider_ns = boa_engine::object::ObjectInitializer::new(ctx).build();
  provider_ns.set(
    js_string!("get"),
    NativeFunction::from_fn_ptr(provider::provider_get)
      .to_js_function(ctx.realm()),
    false,
    ctx,
  )?;
  let tooling_ns = boa_engine::object::ObjectInitializer::new(ctx).build();
  tooling_ns.set(
    js_string!("get"),
    NativeFunction::from_fn_ptr(tooling::tooling_get)
      .to_js_function(ctx.realm()),
    false,
    ctx,
  )?;
  let host_ns = boa_engine::object::ObjectInitializer::new(ctx).build();
  host::register_host(&host_ns, ctx)?;
  omw.set(js_string!("provider"), provider_ns, false, ctx)?;
  omw.set(js_string!("tooling"), tooling_ns, false, ctx)?;
  omw.set(js_string!("host"), host_ns, false, ctx)?;
  ctx
    .global_object()
    .set(js_string!("omw"), omw, false, ctx)?;
  Ok(())
}

fn parse_js(script: &str) -> Result<(), JsError> {
  let mut ctx = Context::default();
  boa_engine::Script::parse(Source::from_bytes(script), None, &mut ctx)
    .map(|_| ())
}

fn eval_js(script: &str) -> Result<Option<String>, JsError> {
  let mut ctx = Context::default();
  install_ctx(&mut ctx)?;
  let value: JsValue = ctx.eval(Source::from_bytes(script))?;
  ctx.run_jobs()?;
  if value.is_undefined() || value.is_null() {
    return Ok(None);
  }
  // Stringify via JSON so arrays/objects surface as `[]`/`{...}`: plain
  // `to_string` would join an array's elements (`[].toString() == ""`).
  match value.to_json(&mut ctx)? {
    None => Ok(None),
    Some(serde_json::Value::String(s)) => Ok(Some(s)),
    Some(json) => serde_json::to_string(&json)
      .map(Some)
      .map_err(|e| crate::convert::js_err(e.to_string())),
  }
}
