// The WASM component export ABI generated by `export!` necessarily uses
// `unsafe` (`#[unsafe(export_name)]` shims), so `unsafe_code` cannot be
// denied in this crate.
#![deny(
  clippy::unwrap_used,
  clippy::expect_used,
  clippy::panic,
  clippy::unreachable
)]
#![deny(clippy::arithmetic_side_effects)]
#![deny(clippy::todo)]
#![deny(clippy::allow_attributes_without_reason)]

//! Rust guest SDK for `omw` wasm brains.
//!
//! Re-exports the generated WIT bindings for the `omw` world plus small
//! builders, typed handles, and RAII guards over them. A brain depends on
//! this crate instead of running `wit-bindgen::generate!` itself.
//!
//! ```rust,ignore
//! #![no_main]
//!
//! omw_wasm_rust::brain!(|| {
//!   omw_wasm_rust::host::info("hello from a rust brain");
//!   Ok(())
//! });
//! ```
//!
//! For more control, implement [`Brain`] manually and export it with the
//! generated `export_brain!`:
//!
//! ```rust,ignore
//! #![no_main]
//!
//! struct Component;
//!
//! impl omw_wasm_rust::Brain for Component {
//!   fn run() -> Result<(), String> {
//!     Ok(())
//!   }
//! }
//!
//! omw_wasm_rust::export_brain!(Component);
//! ```
//!
//! Build the brain for `wasm32-wasip2` and point an agent at it:
//!
//! ```toml
//! [runtime.wasm]
//! kind = "wasm"
//!
//! [[agents]]
//! name = "server"
//! runtime = "wasm"
//! script = "brain.wasm"
//! ```

wit_bindgen::generate!({
    world: "omw",
    path: "wit",
    pub_export_macro: true,
    export_macro_name: "export_brain",
    default_bindings_module: "omw_wasm_rust",
});

/// The `runtime` interface every brain component exports.
pub use exports::omw::omw::runtime::Guest;

/// The trait brains implement instead of [`Guest`].
///
/// The wasm runtime bakes the program into the component, so the `script`
/// argument, `kind`, and `check` are host-side concerns the SDK answers on
/// the brain's behalf: `kind` is always `"wasm"`, `check` always passes,
/// and a finished run is `Completed` (brains that want to exit terminally
/// should loop forever or abort instead).
///
/// Most brains skip this and use [`brain!`] instead, which emits the impl
/// from a closure or function reference. Implement this directly only to
/// customize future extension points while keeping the same export.
pub trait Brain {
  /// Run one iteration of the brain.
  fn run() -> Result<(), String>;
}

impl<T: Brain> Guest for T {
  fn kind() -> String {
    "wasm".to_string()
  }

  fn run(_script: String) -> Result<Option<String>, String> {
    T::run().map(|()| None)
  }

  fn check(_script: String) -> Result<(), String> {
    Ok(())
  }
}

/// Define and export a brain from a closure or function reference.
///
/// Emits a hidden [`Brain`] impl that calls the given expression as
/// `() -> Result<(), String>`, then exports it through the generated
/// `export_brain!`. The closure must not capture its environment, since
/// [`Brain::run`] takes no arguments.
#[macro_export]
macro_rules! brain {
  ($run:expr) => {
    struct __OmwBrain;
    impl $crate::Brain for __OmwBrain {
      fn run() -> Result<(), String> {
        ($run)()
      }
    }
    $crate::export_brain!(__OmwBrain);
  };
}

pub mod host;
pub mod provider;
pub mod tooling;
pub mod types;

/// Common imports for brains.
pub mod prelude {
  pub use crate::Brain;
  pub use crate::omw::omw::types::{
    ChatDelta, ChatMessage, ChatResult, EndpointMessage, EndpointSessionEnd,
    Event, EventEnvelope, ResourceContent, ResourceInfo, Role, Tool, ToolCall,
    ToolResult,
  };
  pub use crate::provider::Provider;
  pub use crate::tooling::Tooling;
}
