// The WASM component export ABI generated by `export!` necessarily uses
// `unsafe` (`#[unsafe(export_name)]` shims), so `unsafe_code` cannot be denied
// in this crate.
#![deny(
  clippy::unwrap_used,
  clippy::expect_used,
  clippy::panic,
  clippy::unreachable
)]
#![deny(clippy::arithmetic_side_effects)]
#![deny(clippy::todo)]
#![deny(clippy::allow_attributes_without_reason)]
#![no_main]

//! The bundled rhai evaluator component.
//!
//! Compiles to `wasm32-wasip2` and exports `omw:omw/runtime`: `run(script)`
//! evaluates the agent's `.rhai` script. Inside a script, the `omw.provider`,
//! `omw.tooling` and `omw.host` tables are provided by the modules built in
//! `install_omw`; each call routes to the host through the generated imports.
//!
//! Provider/tooling instances are looked up by name with `get`, which returns
//! an object map holding the configured name plus function pointers for its
//! methods, so scripts can call them method-style (`p.chat(...)`,
//! `t.call_tool(...)`).

wit_bindgen::generate!({
    world: "omw",
    path: "../../native/omw/wit",
});

use rhai_rt::{
  Array, Dynamic, Engine, EvalAltResult, FnPtr, Map, Module, Position,
};

/// The `runtime` interface is our export.
use crate::exports::omw::omw::runtime::Guest;
/// The three `omw` interfaces are imports (implemented by the host).
use crate::omw::omw::{host, provider, tooling, types};

/// Our exported world implementation.
struct Component;

impl Guest for Component {
  fn kind() -> String {
    "rhai".to_string()
  }

  fn run(script: String) -> Result<Option<String>, String> {
    eval_rhai(&script)
  }
}

export!(Component);

fn eval_rhai(script: &str) -> Result<Option<String>, String> {
  let mut engine = Engine::new();
  install_omw(&mut engine);

  let result: Dynamic = engine.eval(script).map_err(|e| e.to_string())?;
  if result.is_unit() {
    Ok(None)
  } else {
    Ok(Some(result.to_string()))
  }
}

/// Register the `omw` static module and its `provider`/`tooling`/`host`
/// sub-modules with the engine, plus the handle method implementations.
fn install_omw(engine: &mut Engine) {
  engine.register_fn("provider_chat", provider_chat);
  engine.register_fn("provider_is_open", provider_is_open);
  engine.register_fn("provider_cancel", provider_cancel);
  engine.register_fn("provider_models", provider_models);
  engine.register_fn("provider_kind", provider_kind);
  engine.register_fn("tooling_list_tools", tooling_list_tools);
  engine.register_fn("tooling_call_tool", tooling_call_tool);
  engine.register_fn("tooling_kind", tooling_kind);
  engine.register_fn("tooling_list_resources", tooling_list_resources);
  engine.register_fn(
    "tooling_subscribe_resource_list",
    tooling_subscribe_resource_list,
  );
  engine.register_fn("tooling_subscribe_resource", tooling_subscribe_resource);

  let mut provider = Module::new();
  provider.set_native_fn("get", provider_get);

  let mut tooling = Module::new();
  tooling.set_native_fn("get", tooling_get);

  let mut host = Module::new();
  host.set_native_fn("log", host_log);
  host.set_native_fn("now", host_now);
  host.set_native_fn("timestamp_add", host_timestamp_add);
  host.set_native_fn("timestamp_sub", host_timestamp_sub);
  host.set_native_fn("timestamp_diff", host_timestamp_diff);
  host.set_native_fn("timestamp_format", host_timestamp_format);
  host.set_native_fn("wait_timestamp", host_wait_timestamp);
  host.set_native_fn("wait_duration", host_wait_duration);
  host.set_native_fn("wait_cron", host_wait_cron);
  host.set_native_fn("subscribe", host_subscribe);
  host.set_native_fn("send", host_send);
  host.set_native_fn("recv", host_recv);
  host.set_native_fn("try_recv", host_try_recv);
  host.set_native_fn("new_uuid", host_new_uuid);

  let mut omw = Module::new();
  omw.set_sub_module("provider", provider);
  omw.set_sub_module("tooling", tooling);
  omw.set_sub_module("host", host);
  engine.register_static_module("omw", omw.into());
}

// ---------------------------------------------------------------------------
// provider
// ---------------------------------------------------------------------------

/// Look up a provider by name and return an object map with its methods.
fn provider_get(name: &str) -> Result<Map, Box<EvalAltResult>> {
  provider::get(name).map_err(to_error)?;
  let mut m = Map::new();
  m.insert("name".into(), name.into());
  m.insert("chat".into(), method("provider_chat")?.into());
  m.insert("is_open".into(), method("provider_is_open")?.into());
  m.insert("cancel".into(), method("provider_cancel")?.into());
  m.insert("models".into(), method("provider_models")?.into());
  m.insert("kind".into(), method("provider_kind")?.into());
  Ok(m)
}

fn provider_chat(
  handle: Map,
  model: &str,
  messages: Array,
  tools: Array,
) -> Result<String, Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  let p = provider::get(&name).map_err(to_error)?;
  let msgs = messages
    .into_iter()
    .map(msg_from_dynamic)
    .collect::<Result<Vec<_>, _>>()
    .map_err(to_error)?;
  let tls = tools
    .into_iter()
    .map(tool_from_dynamic)
    .collect::<Result<Vec<_>, _>>()
    .map_err(to_error)?;
  p.chat(model, &msgs, &tls).map_err(to_error)
}

fn provider_is_open(
  handle: Map,
  uuid: &str,
) -> Result<bool, Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  Ok(provider::get(&name).map_err(to_error)?.is_open(uuid))
}

fn provider_cancel(handle: Map, uuid: &str) -> Result<(), Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  provider::get(&name).map_err(to_error)?.cancel(uuid);
  Ok(())
}

fn provider_models(handle: Map) -> Result<Array, Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  let models = provider::get(&name).map_err(to_error)?.models();
  Ok(models.into_iter().map(|m| m.into()).collect())
}

fn provider_kind(handle: Map) -> Result<String, Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  Ok(provider::get(&name).map_err(to_error)?.kind())
}

// ---------------------------------------------------------------------------
// tooling
// ---------------------------------------------------------------------------

/// Look up a tooling by name and return an object map with its methods.
fn tooling_get(name: &str) -> Result<Map, Box<EvalAltResult>> {
  tooling::get(name).map_err(to_error)?;
  let mut m = Map::new();
  m.insert("name".into(), name.into());
  m.insert("list_tools".into(), method("tooling_list_tools")?.into());
  m.insert("call_tool".into(), method("tooling_call_tool")?.into());
  m.insert("kind".into(), method("tooling_kind")?.into());
  m.insert(
    "list_resources".into(),
    method("tooling_list_resources")?.into(),
  );
  m.insert(
    "subscribe_resource_list".into(),
    method("tooling_subscribe_resource_list")?.into(),
  );
  m.insert(
    "subscribe_resource".into(),
    method("tooling_subscribe_resource")?.into(),
  );
  Ok(m)
}

fn tooling_list_tools(handle: Map) -> Result<Array, Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  let tools = tooling::get(&name)
    .map_err(to_error)?
    .list_tools()
    .map_err(to_error)?;
  let mut arr = Array::new();
  for t in tools {
    let mut m = Map::new();
    m.insert("name".into(), t.name.into());
    if let Some(desc) = t.description {
      m.insert("description".into(), desc.into());
    }
    m.insert("input_schema".into(), t.input_schema.into());
    arr.push(m.into());
  }
  Ok(arr)
}

fn tooling_call_tool(
  handle: Map,
  tool: &str,
  args: Map,
) -> Result<String, Box<EvalAltResult>> {
  let instance = handle_name(&handle)?;
  let t = tooling::get(&instance).map_err(to_error)?;
  let arguments = json_from_map(&args).map_err(to_error)?;
  t.call_tool(tool, &arguments).map_err(to_error)
}

fn tooling_kind(handle: Map) -> Result<String, Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  Ok(tooling::get(&name).map_err(to_error)?.kind())
}

fn tooling_list_resources(handle: Map) -> Result<Array, Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  let resources = tooling::get(&name)
    .map_err(to_error)?
    .list_resources()
    .map_err(to_error)?;
  let mut arr = Array::new();
  for r in resources {
    let mut m = Map::new();
    m.insert("uri".into(), r.uri.into());
    m.insert("name".into(), r.name.into());
    if let Some(desc) = r.description {
      m.insert("description".into(), desc.into());
    }
    if let Some(mime) = r.mime_type {
      m.insert("mime_type".into(), mime.into());
    }
    arr.push(m.into());
  }
  Ok(arr)
}

fn tooling_subscribe_resource_list(
  handle: Map,
) -> Result<String, Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  tooling::get(&name)
    .map_err(to_error)?
    .subscribe_resource_list()
    .map_err(to_error)
}

fn tooling_subscribe_resource(
  handle: Map,
  uri: &str,
) -> Result<String, Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  tooling::get(&name)
    .map_err(to_error)?
    .subscribe_resource(uri)
    .map_err(to_error)
}

// ---------------------------------------------------------------------------
// host helpers
// ---------------------------------------------------------------------------

fn host_log(level: &str, message: &str) -> Result<(), Box<EvalAltResult>> {
  host::log(level, message);
  Ok(())
}

// The time helpers take/return rhai `i64` (rhai's default integer type) and
// convert at the boundary to the WIT `u64`/`s64`, so scripts can pass plain
// integer literals.
fn host_now() -> Result<i64, Box<EvalAltResult>> {
  i64::try_from(host::now()).map_err(to_error)
}

fn host_timestamp_add(ts: i64, ms: i64) -> Result<i64, Box<EvalAltResult>> {
  let out = host::timestamp_add(to_u64(ts)?, to_u64(ms)?);
  i64::try_from(out).map_err(to_error)
}

fn host_timestamp_sub(ts: i64, ms: i64) -> Result<i64, Box<EvalAltResult>> {
  let out = host::timestamp_sub(to_u64(ts)?, to_u64(ms)?);
  i64::try_from(out).map_err(to_error)
}

fn host_timestamp_diff(a: i64, b: i64) -> Result<i64, Box<EvalAltResult>> {
  Ok(host::timestamp_diff(to_u64(a)?, to_u64(b)?))
}

fn host_timestamp_format(
  ts: i64,
  format: &str,
) -> Result<String, Box<EvalAltResult>> {
  Ok(host::timestamp_format(to_u64(ts)?, format))
}

fn host_wait_timestamp(ts: i64) -> Result<String, Box<EvalAltResult>> {
  host::wait_timestamp(to_u64(ts)?).map_err(to_error)
}

fn host_wait_duration(ms: i64) -> Result<String, Box<EvalAltResult>> {
  host::wait_duration(to_u64(ms)?).map_err(to_error)
}

fn host_wait_cron(spec: &str) -> Result<String, Box<EvalAltResult>> {
  host::wait_cron(spec).map_err(to_error)
}

/// Convert a rhai `i64` to a WIT `u64`, rejecting negatives.
fn to_u64(v: i64) -> Result<u64, Box<EvalAltResult>> {
  u64::try_from(v).map_err(|_| to_error("expected a non-negative integer"))
}

fn host_subscribe(agent: &str) -> Result<String, Box<EvalAltResult>> {
  host::subscribe(agent).map_err(to_error)
}

fn host_send(agent: &str, payload: &str) -> Result<(), Box<EvalAltResult>> {
  host::send(agent, payload);
  Ok(())
}

fn host_recv() -> Result<Map, Box<EvalAltResult>> {
  let envelope = host::recv().map_err(to_error)?;
  Ok(envelope_to_map(envelope))
}

fn host_try_recv() -> Result<Dynamic, Box<EvalAltResult>> {
  let envelope = host::try_recv().map_err(to_error)?;
  let value: Dynamic = match envelope {
    Some(envelope) => envelope_to_map(envelope).into(),
    None => ().into(),
  };
  Ok(value)
}

fn host_new_uuid() -> Result<String, Box<EvalAltResult>> {
  Ok(host::new_uuid())
}

/// Map a `host::EventEnvelope` into a rhai map `#{ id, kind, payload }` so
/// scripts can inspect `e.id` and match events against their handles.
fn envelope_to_map(envelope: host::EventEnvelope) -> Map {
  let mut m = Map::new();
  m.insert("id".into(), envelope.id.into());
  let (kind, payload): (&str, Dynamic) = match envelope.event {
    types::Event::Message(payload) => ("message", payload.into()),
    types::Event::Error(message) => ("error", message.into()),
    types::Event::Timer => ("timer", ().into()),
    types::Event::Delta(delta) => ("delta", delta_to_map(delta).into()),
    types::Event::StreamEnd => ("stream-end", ().into()),
    types::Event::ResourceChanged => ("resource-changed", ().into()),
    types::Event::ResourceUpdated => ("resource-updated", ().into()),
  };
  m.insert("kind".into(), kind.into());
  m.insert("payload".into(), payload);
  m
}

/// Map a `types::ChatDelta` into a rhai map so scripts can read `content`,
/// `tool_call` and `finish_reason` off a `"delta"` event's payload.
fn delta_to_map(delta: types::ChatDelta) -> Map {
  let mut m = Map::new();
  if let Some(content) = delta.content {
    m.insert("content".into(), content.into());
  }
  if let Some(tc) = delta.tool_call {
    let mut t = Map::new();
    t.insert("id".into(), tc.id.into());
    t.insert("name".into(), tc.name.into());
    t.insert("arguments".into(), tc.arguments.into());
    m.insert("tool_call".into(), t.into());
  }
  if let Some(finish_reason) = delta.finish_reason {
    m.insert("finish_reason".into(), finish_reason.into());
  }
  m
}

// ---------------------------------------------------------------------------
// conversion helpers
// ---------------------------------------------------------------------------

/// A method function pointer stored on a handle map.
fn method(name: &str) -> Result<FnPtr, Box<EvalAltResult>> {
  FnPtr::new(name).map_err(to_error)
}

/// Read the configured name back out of a handle map.
fn handle_name(handle: &Map) -> Result<String, Box<EvalAltResult>> {
  handle
    .get("name")
    .and_then(|n| n.clone().try_cast::<String>())
    .ok_or_else(|| to_error("handle map missing name"))
}

fn msg_from_dynamic(d: Dynamic) -> Result<provider::ChatMessage, String> {
  let map = d
    .try_cast::<Map>()
    .ok_or_else(|| "chat message must be a map".to_string())?;
  let role = map
    .get("role")
    .and_then(|r| r.clone().try_cast::<String>())
    .unwrap_or_else(|| "user".to_string());
  let content = map
    .get("content")
    .and_then(|c| c.clone().try_cast::<String>());
  let role_enum = match role.as_str() {
    "system" => provider::Role::System,
    "assistant" => provider::Role::Assistant,
    "tool" => provider::Role::Tool,
    _ => provider::Role::User,
  };
  Ok(provider::ChatMessage {
    role: role_enum,
    content,
    tool_call: None,
  })
}

fn tool_from_dynamic(d: Dynamic) -> Result<provider::Tool, String> {
  let map = d
    .try_cast::<Map>()
    .ok_or_else(|| "tool must be a map".to_string())?;
  let name = map
    .get("name")
    .and_then(|n| n.clone().try_cast::<String>())
    .ok_or_else(|| "tool missing name".to_string())?;
  let description = map
    .get("description")
    .and_then(|d| d.clone().try_cast::<String>());
  let input_schema = map
    .get("input_schema")
    .and_then(|s| s.clone().try_cast::<String>())
    .unwrap_or_else(|| "{}".to_string());
  Ok(provider::Tool {
    name,
    description,
    input_schema,
  })
}

fn to_error(e: impl std::fmt::Display) -> Box<EvalAltResult> {
  Box::new(EvalAltResult::ErrorRuntime(
    e.to_string().into(),
    Position::NONE,
  ))
}

fn json_from_map(map: &Map) -> Result<String, String> {
  let mut parts = Vec::new();
  for (k, v) in map {
    parts.push(format!(
      "{}:{}",
      json_quote(k.as_str()),
      dynamic_to_json(v)?
    ));
  }
  Ok(format!("{{{}}}", parts.join(",")))
}

/// Serialize a rhai value as a JSON fragment, properly escaping strings.
fn dynamic_to_json(v: &Dynamic) -> Result<String, String> {
  if v.is_unit() {
    Ok("null".to_string())
  } else if let Some(s) = v.clone().try_cast::<String>() {
    Ok(json_quote(&s))
  } else if let Some(i) = v.clone().try_cast::<i64>() {
    Ok(i.to_string())
  } else if let Some(f) = v.clone().try_cast::<f64>() {
    Ok(f.to_string())
  } else if let Some(b) = v.clone().try_cast::<bool>() {
    Ok(b.to_string())
  } else if let Some(arr) = v.clone().try_cast::<Array>() {
    let items = arr
      .iter()
      .map(dynamic_to_json)
      .collect::<Result<Vec<_>, _>>()?;
    Ok(format!("[{}]", items.join(",")))
  } else if let Some(map) = v.clone().try_cast::<Map>() {
    let mut parts = Vec::new();
    for (k, val) in &map {
      parts.push(format!(
        "{}:{}",
        json_quote(k.as_str()),
        dynamic_to_json(val)?
      ));
    }
    Ok(format!("{{{}}}", parts.join(",")))
  } else {
    Ok(json_quote(&v.to_string()))
  }
}

/// Quote a string as a JSON string literal, escaping special characters.
fn json_quote(s: &str) -> String {
  let mut out = String::from("\"");
  for c in s.chars() {
    match c {
      '"' => out.push_str("\\\""),
      '\\' => out.push_str("\\\\"),
      '\n' => out.push_str("\\n"),
      '\r' => out.push_str("\\r"),
      '\t' => out.push_str("\\t"),
      c if c <= '\u{1f}' => out.push_str(&format!("\\u{:04x}", c as u32)),
      c => out.push(c),
    }
  }
  out.push('"');
  out
}
