// The WASM component export ABI generated by `export!` necessarily uses
// `unsafe` (`#[unsafe(export_name)]` shims), so `unsafe_code` cannot be denied
// in this crate.
#![deny(
  clippy::unwrap_used,
  clippy::expect_used,
  clippy::panic,
  clippy::unreachable
)]
#![deny(clippy::arithmetic_side_effects)]
#![deny(clippy::todo)]
#![deny(clippy::allow_attributes_without_reason)]
#![no_main]

//! The bundled rhai evaluator component.
//!
//! Compiles to `wasm32-wasip2` and exports `omw:omw/runtime`: `run(script)`
//! evaluates the agent's `.rhai` script. Inside a script, the `omw.provider`,
//! `omw.tooling` and `omw.host` tables are provided by the modules built in
//! `install_omw`; each call routes to the host through the generated imports.
//!
//! Provider/tooling instances are looked up by name with `get`, which returns
//! an object map holding the configured name plus function pointers for its
//! methods, so scripts can call them method-style (`p.chat(...)`,
//! `t.call_tool(...)`).

wit_bindgen::generate!({
    world: "omw",
    path: "../../native/omw/wit",
});

use rhai_rt::{
  Array, Blob, Dynamic, Engine, EvalAltResult, FnPtr, Map, Module, Position,
};

/// The `runtime` interface is our export.
use crate::exports::omw::omw::runtime::Guest;
/// The three `omw` interfaces are imports (implemented by the host).
use crate::omw::omw::{host, provider, tooling, types};

/// Our exported world implementation.
struct Component;

impl Guest for Component {
  fn kind() -> String {
    "rhai".to_string()
  }

  fn run(script: String) -> Result<Option<String>, String> {
    eval_rhai(&script)
  }

  fn check(script: String) -> Result<(), String> {
    let mut engine = Engine::new();
    install_omw(&mut engine);
    engine
      .compile(&script)
      .map(|_| ())
      .map_err(|e| e.to_string())
  }
}

export!(Component);

fn eval_rhai(script: &str) -> Result<Option<String>, String> {
  let mut engine = Engine::new();
  install_omw(&mut engine);

  let result: Dynamic = engine.eval(script).map_err(|e| e.to_string())?;
  if result.is_unit() {
    Ok(None)
  } else {
    Ok(Some(result.to_string()))
  }
}

/// Register the `omw` static module and its `provider`/`tooling`/`host`
/// sub-modules with the engine, plus the handle method implementations.
fn install_omw(engine: &mut Engine) {
  engine.register_fn("provider_chat", provider_chat);
  engine.register_fn("provider_chat_stream", provider_chat_stream);
  engine.register_fn("provider_is_open", provider_is_open);
  engine.register_fn("provider_cancel", provider_cancel);
  engine.register_fn("provider_models", provider_models);
  engine.register_fn("provider_kind", provider_kind);
  engine.register_fn("tooling_list_tools", tooling_list_tools);
  engine.register_fn("tooling_call_tool", tooling_call_tool);
  engine.register_fn("tooling_call_tool_blocking", tooling_call_tool_blocking);
  engine.register_fn("tooling_is_open", tooling_is_open);
  engine.register_fn("tooling_cancel", tooling_cancel);
  engine.register_fn("tooling_kind", tooling_kind);
  engine.register_fn("tooling_list_resources", tooling_list_resources);
  engine.register_fn("tooling_read_resource", tooling_read_resource);
  engine.register_fn(
    "tooling_subscribe_resource_list",
    tooling_subscribe_resource_list,
  );
  engine.register_fn("tooling_subscribe_resource", tooling_subscribe_resource);
  engine.register_fn(
    "tooling_unsubscribe_resource_list",
    tooling_unsubscribe_resource_list,
  );
  engine
    .register_fn("tooling_unsubscribe_resource", tooling_unsubscribe_resource);

  let mut provider = Module::new();
  provider.set_native_fn("get", provider_get);

  let mut tooling = Module::new();
  tooling.set_native_fn("get", tooling_get);

  let mut host = Module::new();
  host.set_native_fn("log", host_log);
  host.set_native_fn("now", host_now);
  host.set_native_fn("timestamp_add", host_timestamp_add);
  host.set_native_fn("timestamp_sub", host_timestamp_sub);
  host.set_native_fn("timestamp_diff", host_timestamp_diff);
  host.set_native_fn("timestamp_format", host_timestamp_format);
  host.set_native_fn("wait_timestamp", host_wait_timestamp);
  host.set_native_fn("wait_duration", host_wait_duration);
  host.set_native_fn("wait_cron", host_wait_cron);
  host.set_native_fn("sleep_duration", host_sleep_duration);
  host.set_native_fn("sleep_timestamp", host_sleep_timestamp);
  host.set_native_fn("sleep_cron", host_sleep_cron);
  host.set_native_fn("cancel", host_cancel);
  host.set_native_fn("subscribe", host_subscribe);
  host.set_native_fn("unsubscribe", host_unsubscribe);
  host.set_native_fn("lifecycle_subscribe", host_lifecycle_subscribe);
  host.set_native_fn("lifecycle_unsubscribe", host_lifecycle_unsubscribe);
  host.set_native_fn("send", host_send);
  host.set_native_fn("recv", host_recv);
  host.set_native_fn("try_recv", host_try_recv);
  host.set_native_fn("new_uuid", host_new_uuid);
  host.set_native_fn("base64_encode", host_base64_encode);
  host.set_native_fn("base64_decode", host_base64_decode);
  host.set_native_fn("memory_get", host_memory_get);
  host.set_native_fn("memory_set", host_memory_set);
  host.set_native_fn("memory_del", host_memory_del);

  host.set_native_fn("endpoint_subscribe", host_endpoint_subscribe);
  host.set_native_fn("endpoint_unsubscribe", host_endpoint_unsubscribe);
  host.set_native_fn("endpoint_stream", host_endpoint_stream);
  let mut omw = Module::new();
  omw.set_sub_module("provider", provider);
  omw.set_sub_module("tooling", tooling);
  omw.set_sub_module("host", host);
  engine.register_static_module("omw", omw.into());
}

// ---------------------------------------------------------------------------
// provider
// ---------------------------------------------------------------------------

/// Look up a provider by name and return an object map with its methods.
fn provider_get(name: &str) -> Result<Map, Box<EvalAltResult>> {
  provider::get(name).map_err(to_error)?;
  let mut m = Map::new();
  m.insert("name".into(), name.into());
  m.insert("chat".into(), method("provider_chat")?.into());
  m.insert("chat_stream".into(), method("provider_chat_stream")?.into());
  m.insert("is_open".into(), method("provider_is_open")?.into());
  m.insert("cancel".into(), method("provider_cancel")?.into());
  m.insert("models".into(), method("provider_models")?.into());
  m.insert("kind".into(), method("provider_kind")?.into());
  Ok(m)
}

fn provider_chat_stream(
  handle: Map,
  model: &str,
  messages: Array,
  tools: Array,
) -> Result<String, Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  let p = provider::get(&name).map_err(to_error)?;
  let msgs = messages
    .into_iter()
    .map(msg_from_dynamic)
    .collect::<Result<Vec<_>, _>>()
    .map_err(to_error)?;
  let tls = tools
    .into_iter()
    .map(tool_from_dynamic)
    .collect::<Result<Vec<_>, _>>()
    .map_err(to_error)?;
  let result = p.chat_stream(model, &msgs, &tls);
  result.map_err(to_error)
}

fn provider_chat(
  handle: Map,
  model: &str,
  messages: Array,
  tools: Array,
) -> Result<Map, Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  let p = provider::get(&name).map_err(to_error)?;
  let msgs = messages
    .into_iter()
    .map(msg_from_dynamic)
    .collect::<Result<Vec<_>, _>>()
    .map_err(to_error)?;
  let tls = tools
    .into_iter()
    .map(tool_from_dynamic)
    .collect::<Result<Vec<_>, _>>()
    .map_err(to_error)?;
  let result = p.chat(model, &msgs, &tls)?;
  Ok(chat_result_to_map(result))
}

fn provider_is_open(
  handle: Map,
  uuid: &str,
) -> Result<bool, Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  Ok(provider::get(&name).map_err(to_error)?.is_open(uuid))
}

fn provider_cancel(handle: Map, uuid: &str) -> Result<(), Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  provider::get(&name).map_err(to_error)?.cancel(uuid);
  Ok(())
}

fn provider_models(handle: Map) -> Result<Array, Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  let models = provider::get(&name).map_err(to_error)?.models();
  Ok(models.into_iter().map(|m| m.into()).collect())
}

fn provider_kind(handle: Map) -> Result<String, Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  Ok(provider::get(&name).map_err(to_error)?.kind())
}

// ---------------------------------------------------------------------------
// tooling
// ---------------------------------------------------------------------------

/// Look up a tooling by name and return an object map with its methods.
fn tooling_get(name: &str) -> Result<Map, Box<EvalAltResult>> {
  tooling::get(name).map_err(to_error)?;
  let mut m = Map::new();
  m.insert("name".into(), name.into());
  m.insert("list_tools".into(), method("tooling_list_tools")?.into());
  m.insert("call_tool".into(), method("tooling_call_tool")?.into());
  m.insert(
    "call_tool_blocking".into(),
    method("tooling_call_tool_blocking")?.into(),
  );
  m.insert("is_open".into(), method("tooling_is_open")?.into());
  m.insert("cancel".into(), method("tooling_cancel")?.into());
  m.insert("kind".into(), method("tooling_kind")?.into());
  m.insert(
    "list_resources".into(),
    method("tooling_list_resources")?.into(),
  );
  m.insert(
    "read_resource".into(),
    method("tooling_read_resource")?.into(),
  );
  m.insert(
    "subscribe_resource_list".into(),
    method("tooling_subscribe_resource_list")?.into(),
  );
  m.insert(
    "subscribe_resource".into(),
    method("tooling_subscribe_resource")?.into(),
  );
  Ok(m)
}

fn tooling_list_tools(handle: Map) -> Result<Array, Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  let tools = tooling::get(&name)
    .map_err(to_error)?
    .list_tools()
    .map_err(to_error)?;
  let mut arr = Array::new();
  for t in tools {
    let mut m = Map::new();
    m.insert("name".into(), t.name.into());
    if let Some(desc) = t.description {
      m.insert("description".into(), desc.into());
    }
    m.insert("input_schema".into(), t.input_schema.into());
    arr.push(m.into());
  }
  Ok(arr)
}

fn tooling_call_tool(
  handle: Map,
  tool: &str,
  args: Map,
) -> Result<String, Box<EvalAltResult>> {
  let instance = handle_name(&handle)?;
  let t = tooling::get(&instance).map_err(to_error)?;
  let arguments = json_from_map(&args).map_err(to_error)?;
  t.call_tool(tool, &arguments).map_err(to_error)
}

fn tooling_call_tool_blocking(
  handle: Map,
  tool: &str,
  args: Map,
) -> Result<Map, Box<EvalAltResult>> {
  let instance = handle_name(&handle)?;
  let t = tooling::get(&instance).map_err(to_error)?;
  let arguments = json_from_map(&args).map_err(to_error)?;
  let result = t.call_tool_blocking(tool, &arguments).map_err(to_error)?;
  Ok(tool_result_to_map(result))
}

fn tooling_is_open(
  handle: Map,
  uuid: &str,
) -> Result<bool, Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  Ok(tooling::get(&name).map_err(to_error)?.is_open(uuid))
}

fn tooling_cancel(handle: Map, uuid: &str) -> Result<(), Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  tooling::get(&name).map_err(to_error)?.cancel(uuid);
  Ok(())
}

fn tooling_kind(handle: Map) -> Result<String, Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  Ok(tooling::get(&name).map_err(to_error)?.kind())
}

fn tooling_list_resources(handle: Map) -> Result<Array, Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  let resources = tooling::get(&name)
    .map_err(to_error)?
    .list_resources()
    .map_err(to_error)?;
  let mut arr = Array::new();
  for r in resources {
    arr.push(resource_to_map(r).into());
  }
  Ok(arr)
}

fn tooling_read_resource(
  handle: Map,
  uri: &str,
) -> Result<Map, Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  let content = tooling::get(&name)
    .map_err(to_error)?
    .read_resource(uri)
    .map_err(to_error)?;
  Ok(resource_content_to_map(content))
}

/// Map one `types::ResourceInfo` into a rhai map so scripts can read `uri`,
/// `name`, `description`, and `mime_type` off a resource.
fn resource_to_map(r: types::ResourceInfo) -> Map {
  let mut m = Map::new();
  m.insert("uri".into(), r.uri.into());
  m.insert("name".into(), r.name.into());
  if let Some(desc) = r.description {
    m.insert("description".into(), desc.into());
  }
  if let Some(mime) = r.mime_type {
    m.insert("mime_type".into(), mime.into());
  }
  m
}

/// Map one `types::ToolResult` into a rhai map so scripts can read `name`,
/// `arguments` and `value` off a tool-call result.
fn tool_result_to_map(r: types::ToolResult) -> Map {
  let mut m = Map::new();
  m.insert("name".into(), r.name.into());
  m.insert("arguments".into(), r.arguments.into());
  m.insert("value".into(), r.value.into());
  m
}

/// Map a `types::ChatResult` into a rhai map so scripts can read `content`,
/// `tool_calls`, and `finish_reason` off a blocking `chat` result.
fn chat_result_to_map(r: types::ChatResult) -> Map {
  let mut m = Map::new();
  if let Some(content) = r.content {
    m.insert("content".into(), content.into());
  }
  let mut calls = Array::new();
  for tc in r.tool_calls {
    let mut t = Map::new();
    t.insert("id".into(), tc.id.into());
    t.insert("name".into(), tc.name.into());
    t.insert("arguments".into(), tc.arguments.into());
    calls.push(t.into());
  }
  m.insert("tool_calls".into(), calls.into());
  if let Some(finish_reason) = r.finish_reason {
    m.insert("finish_reason".into(), finish_reason.into());
  }
  m
}

/// Map one `types::ResourceContent` into a rhai map so scripts can read `uri`,
/// `mime_type` and `content` off a `resource-updated` event.
fn resource_content_to_map(c: types::ResourceContent) -> Map {
  let mut m = Map::new();
  m.insert("uri".into(), c.uri.into());
  if let Some(mime) = c.mime_type {
    m.insert("mime_type".into(), mime.into());
  }
  m.insert("content".into(), c.content.into());
  m
}

fn tooling_subscribe_resource_list(
  handle: Map,
) -> Result<String, Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  tooling::get(&name)
    .map_err(to_error)?
    .subscribe_resource_list()
    .map_err(to_error)
}

fn tooling_subscribe_resource(
  handle: Map,
  uri: &str,
) -> Result<String, Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  tooling::get(&name)
    .map_err(to_error)?
    .subscribe_resource(uri)
    .map_err(to_error)
}

fn tooling_unsubscribe_resource_list(
  handle: Map,
  uuid: &str,
) -> Result<(), Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  tooling::get(&name)
    .map_err(to_error)?
    .unsubscribe_resource_list(uuid);
  Ok(())
}

fn tooling_unsubscribe_resource(
  handle: Map,
  uuid: &str,
) -> Result<(), Box<EvalAltResult>> {
  let name = handle_name(&handle)?;
  tooling::get(&name)
    .map_err(to_error)?
    .unsubscribe_resource(uuid);
  Ok(())
}

// ---------------------------------------------------------------------------
// host helpers
// ---------------------------------------------------------------------------

fn host_log(level: &str, message: &str) -> Result<(), Box<EvalAltResult>> {
  host::log(level, message);
  Ok(())
}

// The time helpers take/return rhai `i64` (rhai's default integer type) and
// convert at the boundary to the WIT `u64`/`s64`, so scripts can pass plain
// integer literals.
fn host_now() -> Result<i64, Box<EvalAltResult>> {
  i64::try_from(host::now()).map_err(to_error)
}

fn host_timestamp_add(ts: i64, ms: i64) -> Result<i64, Box<EvalAltResult>> {
  let out = host::timestamp_add(to_u64(ts)?, to_u64(ms)?);
  i64::try_from(out).map_err(to_error)
}

fn host_timestamp_sub(ts: i64, ms: i64) -> Result<i64, Box<EvalAltResult>> {
  let out = host::timestamp_sub(to_u64(ts)?, to_u64(ms)?);
  i64::try_from(out).map_err(to_error)
}

fn host_timestamp_diff(a: i64, b: i64) -> Result<i64, Box<EvalAltResult>> {
  Ok(host::timestamp_diff(to_u64(a)?, to_u64(b)?))
}

fn host_timestamp_format(
  ts: i64,
  format: &str,
) -> Result<String, Box<EvalAltResult>> {
  Ok(host::timestamp_format(to_u64(ts)?, format))
}

fn host_wait_timestamp(ts: i64) -> Result<String, Box<EvalAltResult>> {
  host::wait_timestamp(to_u64(ts)?).map_err(to_error)
}

fn host_wait_duration(ms: i64) -> Result<String, Box<EvalAltResult>> {
  host::wait_duration(to_u64(ms)?).map_err(to_error)
}

fn host_wait_cron(spec: &str) -> Result<String, Box<EvalAltResult>> {
  host::wait_cron(spec).map_err(to_error)
}

fn host_sleep_duration(ms: i64) -> Result<(), Box<EvalAltResult>> {
  host::sleep_duration(to_u64(ms)?);
  Ok(())
}

fn host_sleep_timestamp(ts: i64) -> Result<(), Box<EvalAltResult>> {
  host::sleep_timestamp(to_u64(ts)?).map_err(to_error)
}

fn host_sleep_cron(spec: &str) -> Result<(), Box<EvalAltResult>> {
  host::sleep_cron(spec).map_err(to_error)
}

fn host_cancel(uuid: &str) -> Result<(), Box<EvalAltResult>> {
  host::cancel(uuid);
  Ok(())
}

fn host_subscribe(agent: &str) -> Result<String, Box<EvalAltResult>> {
  host::subscribe(agent).map_err(to_error)
}

fn host_unsubscribe(uuid: &str) -> Result<(), Box<EvalAltResult>> {
  host::unsubscribe(uuid);
  Ok(())
}

fn host_lifecycle_subscribe() -> Result<String, Box<EvalAltResult>> {
  host::lifecycle_subscribe().map_err(to_error)
}

fn host_lifecycle_unsubscribe(uuid: &str) -> Result<(), Box<EvalAltResult>> {
  host::lifecycle_unsubscribe(uuid);
  Ok(())
}

/// Convert a rhai `i64` to a WIT `u64`, rejecting negatives.
fn to_u64(v: i64) -> Result<u64, Box<EvalAltResult>> {
  u64::try_from(v).map_err(|_| to_error("expected a non-negative integer"))
}

fn host_send(agent: &str, payload: &str) -> Result<(), Box<EvalAltResult>> {
  host::send(agent, payload);
  Ok(())
}

fn host_recv() -> Result<Map, Box<EvalAltResult>> {
  let envelope = host::recv().map_err(to_error)?;
  Ok(envelope_to_map(envelope))
}

fn host_try_recv() -> Result<Dynamic, Box<EvalAltResult>> {
  let envelope = host::try_recv().map_err(to_error)?;
  let value: Dynamic = match envelope {
    Some(envelope) => envelope_to_map(envelope).into(),
    None => ().into(),
  };
  Ok(value)
}

fn host_new_uuid() -> Result<String, Box<EvalAltResult>> {
  Ok(host::new_uuid())
}

/// Encode raw bytes (a rhai blob) as standard padded base64.
fn host_base64_encode(bytes: Blob) -> Result<String, Box<EvalAltResult>> {
  Ok(host::base64_encode(&bytes))
}

/// Decode standard padded base64 back to raw bytes (a rhai blob).
fn host_base64_decode(data: &str) -> Result<Blob, Box<EvalAltResult>> {
  host::base64_decode(data).map_err(to_error)
}

fn host_memory_get(key: &str) -> Result<Dynamic, Box<EvalAltResult>> {
  let value: Dynamic = match host::memory_get(key) {
    Some(value) => value.into(),
    None => ().into(),
  };
  Ok(value)
}

fn host_memory_set(key: &str, value: &str) -> Result<(), Box<EvalAltResult>> {
  host::memory_set(key, value);
  Ok(())
}

fn host_memory_del(key: &str) -> Result<bool, Box<EvalAltResult>> {
  Ok(host::memory_del(key))
}

/// Subscribe this agent to the endpoint under the model name `model`. Returns
/// the subscription UUID; inbound endpoint requests arrive as
/// `"endpoint-message"` events tagged with it.
fn host_endpoint_subscribe(model: &str) -> Result<String, Box<EvalAltResult>> {
  host::endpoint_subscribe(model).map_err(to_error)
}

/// Unsubscribe by a UUID that `endpoint_subscribe` returned; the model is
/// dropped and every in-flight session of that subscription is terminated.
fn host_endpoint_unsubscribe(uuid: &str) -> Result<(), Box<EvalAltResult>> {
  host::endpoint_unsubscribe(uuid);
  Ok(())
}

/// Stream one `chat-delta` map to the endpoint session identified by `session`,
/// non-blocking. A map carrying a `finish_reason` ends the session.
fn host_endpoint_stream(
  session: &str,
  delta: Map,
) -> Result<(), Box<EvalAltResult>> {
  let delta = delta_from_map(&delta).map_err(to_error)?;
  host::endpoint_stream(session, &delta).map_err(to_error)
}

/// Map a `host::EventEnvelope` into a rhai map `#{ id, kind, payload }` so
/// scripts can inspect `e.id` and match events against their handles.
fn envelope_to_map(envelope: host::EventEnvelope) -> Map {
  let mut m = Map::new();
  m.insert("id".into(), envelope.id.into());
  let (kind, payload): (&str, Dynamic) = match envelope.event {
    types::Event::Message(payload) => ("message", payload.into()),
    types::Event::Error(message) => ("error", message.into()),
    types::Event::Timer => ("timer", ().into()),
    types::Event::Reload => ("reload", ().into()),
    types::Event::Shutdown => ("shutdown", ().into()),
    types::Event::ChatDelta(delta) => {
      ("chat-delta", delta_to_map(delta).into())
    }
    types::Event::StreamEnd => ("stream-end", ().into()),
    types::Event::ToolResult(result) => {
      ("tool-result", tool_result_to_map(result).into())
    }
    types::Event::ResourceListUpdated(resources) => {
      let mut arr = Array::new();
      for r in resources {
        arr.push(resource_to_map(r).into());
      }
      ("resource-list-updated", arr.into())
    }
    types::Event::ResourceUpdated(content) => {
      ("resource-updated", resource_content_to_map(content).into())
    }
    types::Event::EndpointMessage(message) => {
      let mut payload = Map::new();
      payload.insert("session".into(), message.session.into());
      let mut messages = Array::new();
      for m in message.messages {
        messages.push(chat_message_to_map(m).into());
      }
      payload.insert("messages".into(), messages.into());
      let mut tools = Array::new();
      for t in message.tools {
        tools.push(tool_to_map(t).into());
      }
      payload.insert("tools".into(), tools.into());
      ("endpoint-message", payload.into())
    }
    types::Event::EndpointSessionEnd(end) => {
      let mut payload = Map::new();
      payload.insert("session".into(), end.session.into());
      if let Some(error) = end.error {
        payload.insert("error".into(), error.into());
      }
      ("endpoint-session-end", payload.into())
    }
  };
  m.insert("kind".into(), kind.into());
  m.insert("payload".into(), payload);
  m
}

/// Map a `types::ChatDelta` into a rhai map so scripts can read `content`,
/// `tool_call` and `finish_reason` off a `"chat-delta"` event's payload.
fn delta_to_map(delta: types::ChatDelta) -> Map {
  let mut m = Map::new();
  if let Some(content) = delta.content {
    m.insert("content".into(), content.into());
  }
  if let Some(tc) = delta.tool_call {
    let mut t = Map::new();
    t.insert("id".into(), tc.id.into());
    t.insert("name".into(), tc.name.into());
    t.insert("arguments".into(), tc.arguments.into());
    m.insert("tool_call".into(), t.into());
  }
  if let Some(finish_reason) = delta.finish_reason {
    m.insert("finish_reason".into(), finish_reason.into());
  }
  m
}

/// Map a `types::ChatDelta` back out of a rhai map (the inverse of
/// [`delta_to_map`]). Reads `content`, `tool_call` (a map with `id`/
/// `name`/`arguments`), and `finish_reason` off it.
fn delta_from_map(delta: &Map) -> Result<types::ChatDelta, String> {
  let content = delta
    .get("content")
    .and_then(|c| c.clone().try_cast::<String>());
  let tool_call = match delta.get("tool_call") {
    Some(tc) => {
      let tc = tc
        .clone()
        .try_cast::<Map>()
        .ok_or_else(|| "tool_call must be a map".to_string())?;
      let id = tc
        .get("id")
        .and_then(|v| v.clone().try_cast::<String>())
        .ok_or_else(|| "tool_call missing id".to_string())?;
      let name = tc
        .get("name")
        .and_then(|v| v.clone().try_cast::<String>())
        .ok_or_else(|| "tool_call missing name".to_string())?;
      let arguments = tc
        .get("arguments")
        .and_then(|v| v.clone().try_cast::<String>())
        .ok_or_else(|| "tool_call missing arguments".to_string())?;
      Some(types::ToolCall {
        id,
        name,
        arguments,
      })
    }
    None => None,
  };
  let finish_reason = delta
    .get("finish_reason")
    .and_then(|f| f.clone().try_cast::<String>());
  Ok(types::ChatDelta {
    content,
    tool_call,
    finish_reason,
  })
}

/// Map a `types::ChatMessage` into a rhai map so scripts can read `role`,
/// `content`,and `tool_call` off an `endpoint-message` event's messages.
fn chat_message_to_map(m: types::ChatMessage) -> Map {
  let mut r = Map::new();
  if let Some(content) = m.content {
    r.insert("content".into(), content.into());
  }
  if let Some(tc) = m.tool_call {
    r.insert("tool_call".into(), tool_call_to_map(tc).into());
  }
  let role = match m.role {
    types::Role::System => "system",
    types::Role::User => "user",
    types::Role::Assistant => "assistant",
    types::Role::Tool => "tool",
  };
  r.insert("role".into(), role.into());
  r
}

/// Map a `types::Tool` into a rhai map so scripts can read `name`,
/// `description`,and `input_schema` off an `endpoint-message` event's tools.
fn tool_to_map(t: types::Tool) -> Map {
  let mut m = Map::new();
  if let Some(desc) = t.description {
    m.insert("description".into(), desc.into());
  }
  m.insert("name".into(), t.name.into());
  m.insert("input_schema".into(), t.input_schema.into());
  m
}

/// Map a `types::ToolCall` into a rhai map so scripts can read `id`/
/// `name`/`arguments` off a tool call.
fn tool_call_to_map(tc: types::ToolCall) -> Map {
  let mut m = Map::new();
  m.insert("id".into(), tc.id.into());
  m.insert("name".into(), tc.name.into());
  m.insert("arguments".into(), tc.arguments.into());
  m
}

// ---------------------------------------------------------------------------
// conversion helpers
// ---------------------------------------------------------------------------

/// A method function pointer stored on a handle map.
fn method(name: &str) -> Result<FnPtr, Box<EvalAltResult>> {
  FnPtr::new(name).map_err(to_error)
}

/// Read the configured name back out of a handle map.
fn handle_name(handle: &Map) -> Result<String, Box<EvalAltResult>> {
  handle
    .get("name")
    .and_then(|n| n.clone().try_cast::<String>())
    .ok_or_else(|| to_error("handle map missing name"))
}

fn msg_from_dynamic(d: Dynamic) -> Result<provider::ChatMessage, String> {
  let map = d
    .try_cast::<Map>()
    .ok_or_else(|| "chat message must be a map".to_string())?;
  let role = map
    .get("role")
    .and_then(|r| r.clone().try_cast::<String>())
    .unwrap_or_else(|| "user".to_string());
  let content = map
    .get("content")
    .and_then(|c| c.clone().try_cast::<String>());
  let role_enum = match role.as_str() {
    "system" => provider::Role::System,
    "assistant" => provider::Role::Assistant,
    "tool" => provider::Role::Tool,
    _ => provider::Role::User,
  };
  let tool_call = match map.get("tool_call") {
    Some(tc) => {
      let tc = tc
        .clone()
        .try_cast::<Map>()
        .ok_or_else(|| "tool_call must be a map".to_string())?;
      let id = tc
        .get("id")
        .and_then(|v| v.clone().try_cast::<String>())
        .ok_or_else(|| "tool_call missing id".to_string())?;
      let name = tc
        .get("name")
        .and_then(|v| v.clone().try_cast::<String>())
        .ok_or_else(|| "tool_call missing name".to_string())?;
      let arguments = tc
        .get("arguments")
        .and_then(|v| v.clone().try_cast::<String>())
        .ok_or_else(|| "tool_call missing arguments".to_string())?;
      Some(provider::ToolCall {
        id,
        name,
        arguments,
      })
    }
    None => None,
  };
  Ok(provider::ChatMessage {
    role: role_enum,
    content,
    tool_call,
  })
}

fn tool_from_dynamic(d: Dynamic) -> Result<provider::Tool, String> {
  let map = d
    .try_cast::<Map>()
    .ok_or_else(|| "tool must be a map".to_string())?;
  let name = map
    .get("name")
    .and_then(|n| n.clone().try_cast::<String>())
    .ok_or_else(|| "tool missing name".to_string())?;
  let description = map
    .get("description")
    .and_then(|d| d.clone().try_cast::<String>());
  let input_schema = map
    .get("input_schema")
    .and_then(|s| s.clone().try_cast::<String>())
    .unwrap_or_else(|| "{}".to_string());
  Ok(provider::Tool {
    name,
    description,
    input_schema,
  })
}

fn to_error(e: impl std::fmt::Display) -> Box<EvalAltResult> {
  Box::new(EvalAltResult::ErrorRuntime(
    e.to_string().into(),
    Position::NONE,
  ))
}

fn json_from_map(map: &Map) -> Result<String, String> {
  let mut parts = Vec::new();
  for (k, v) in map {
    parts.push(format!(
      "{}:{}",
      json_quote(k.as_str()),
      dynamic_to_json(v)?
    ));
  }
  Ok(format!("{{{}}}", parts.join(",")))
}

/// Serialize a rhai value as a JSON fragment, properly escaping strings.
fn dynamic_to_json(v: &Dynamic) -> Result<String, String> {
  if v.is_unit() {
    Ok("null".to_string())
  } else if let Some(s) = v.clone().try_cast::<String>() {
    Ok(json_quote(&s))
  } else if let Some(i) = v.clone().try_cast::<i64>() {
    Ok(i.to_string())
  } else if let Some(f) = v.clone().try_cast::<f64>() {
    Ok(f.to_string())
  } else if let Some(b) = v.clone().try_cast::<bool>() {
    Ok(b.to_string())
  } else if let Some(arr) = v.clone().try_cast::<Array>() {
    let items = arr
      .iter()
      .map(dynamic_to_json)
      .collect::<Result<Vec<_>, _>>()?;
    Ok(format!("[{}]", items.join(",")))
  } else if let Some(map) = v.clone().try_cast::<Map>() {
    let mut parts = Vec::new();
    for (k, val) in &map {
      parts.push(format!(
        "{}:{}",
        json_quote(k.as_str()),
        dynamic_to_json(val)?
      ));
    }
    Ok(format!("{{{}}}", parts.join(",")))
  } else {
    Ok(json_quote(&v.to_string()))
  }
}

/// Quote a string as a JSON string literal, escaping special characters.
fn json_quote(s: &str) -> String {
  let mut out = String::from("\"");
  for c in s.chars() {
    match c {
      '"' => out.push_str("\\\""),
      '\\' => out.push_str("\\\\"),
      '\n' => out.push_str("\\n"),
      '\r' => out.push_str("\\r"),
      '\t' => out.push_str("\\t"),
      c if c <= '\u{1f}' => out.push_str(&format!("\\u{:04x}", c as u32)),
      c => out.push(c),
    }
  }
  out.push('"');
  out
}
