"""Type stubs for the `omw` global the bundled `omw-wasm-python-interpreter`
component injects into every python brain script.

Vendor `omw.all.py` (the generated deployment/testing config models, namespaced
under `OmwConfig` / `OmwTestConfig`, plus this file) next to your `brain.py` and
point your type checker at it. See docs/runtime/python.md for the prose
reference.
"""

from typing import Any, Literal, Optional

Role = Literal["system", "user", "assistant", "tool"]

class ToolCall:
  id: str
  name: str
  arguments: Any

class ChatMessage:
  role: Role
  content: Optional[str]
  reasoning: Optional[str]
  tool_call: Optional[ToolCall]

class Usage:
  prompt_tokens: Optional[int]
  completion_tokens: Optional[int]
  total_tokens: Optional[int]

class ChatDelta:
  content: Optional[str]
  reasoning: Optional[str]
  tool_call: Optional[ToolCall]
  finish_reason: Optional[str]
  usage: Optional[Usage]

class Tool:
  name: str
  description: Optional[str]
  input_schema: Any
  output_schema: Any

class ChatResult:
  content: Optional[str]
  reasoning: Optional[str]
  tool_calls: list[ToolCall]
  finish_reason: Optional[str]
  usage: Optional[Usage]

class ToolResult:
  name: str
  arguments: Any
  content: Any
  structured_content: Any

class ResourceInfo:
  uri: str
  name: str
  description: Optional[str]
  mime_type: Optional[str]

class ResourceContent:
  uri: str
  mime_type: Optional[str]
  content: str

class EventEnvelope:
  id: str
  kind: str
  payload: Any

class Provider:
  name: str
  def chat(
    self,
    model: str,
    messages: list[ChatMessage],
    tools: list[Tool],
    params: Any = ...,
  ) -> ChatResult: ...
  def chat_stream(
    self,
    model: str,
    messages: list[ChatMessage],
    tools: list[Tool],
    params: Any = ...,
  ) -> str: ...
  def is_open(self, uuid: str) -> bool: ...
  def cancel(self, uuid: str) -> None: ...
  def list_models(self) -> list[str]: ...
  def kind(self) -> str: ...

class Tooling:
  name: str
  def list_tools(self) -> list[Tool]: ...
  def call_tool(self, tool: str, arguments: Any) -> str: ...
  def call_tool_blocking(self, tool: str, arguments: Any) -> ToolResult: ...
  def is_open(self, uuid: str) -> bool: ...
  def cancel(self, uuid: str) -> None: ...
  def kind(self) -> str: ...
  def list_resources(self) -> list[ResourceInfo]: ...
  def read_resource(self, uri: str) -> ResourceContent: ...
  def subscribe_resource_list(self) -> str: ...
  def subscribe_resource(self, uri: str) -> str: ...
  def unsubscribe_resource_list(self, uuid: str) -> None: ...
  def unsubscribe_resource(self, uuid: str) -> None: ...

class ProviderNamespace:
  def get(self, name: str) -> Provider: ...

class ToolingNamespace:
  def get(self, name: str) -> Tooling: ...

class Host:
  def log(self, level: str, message: str) -> None: ...
  def whoami(self) -> str: ...
  def time_now(self) -> int: ...
  def time_format(self, ts: int, format: str) -> str: ...
  def wait_until(self, ts: int) -> str: ...
  def wait_for(self, ms: int) -> str: ...
  def wait_cron(self, spec: str) -> str: ...
  def sleep_for(self, ms: int) -> None: ...
  def sleep_until(self, ts: int) -> None: ...
  def sleep_cron(self, spec: str) -> None: ...
  def cancel_timer(self, uuid: str) -> None: ...
  def subscribe_agent(self, agent: str) -> str: ...
  def unsubscribe_agent(self, uuid: str) -> None: ...
  def subscribe_lifecycle(self) -> str: ...
  def unsubscribe_lifecycle(self, uuid: str) -> None: ...
  def send_agent(self, agent: str, payload: str) -> None: ...
  def recv(self) -> EventEnvelope: ...
  def try_recv(self) -> Optional[EventEnvelope]: ...
  def new_uuid(self) -> str: ...
  def base64_encode(self, bytes: Any) -> str: ...
  def base64_decode(self, data: str) -> bytes: ...
  def memory_get(self, key: str) -> Optional[str]: ...
  def memory_get_as(self, key: str) -> Any: ...
  def memory_set(self, key: str, value: str) -> None: ...
  def memory_set_as(self, key: str, value: Any) -> None: ...
  def memory_remove(self, key: str) -> bool: ...
  def subscribe_endpoint(self, model: str) -> str: ...
  def unsubscribe_endpoint(self, uuid: str) -> None: ...
  def stream_endpoint(self, session: str, delta: Any) -> None: ...

class Omw:
  host: Host
  provider: ProviderNamespace
  tooling: ToolingNamespace

omw: Omw
