name: release-pr

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  release-pr:
    runs-on: ubuntu-latest
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes auto-allocate-uids cgroups
            auto-allocate-uids = true
      - uses: cachix/cachix-action@v15
        with:
          name: haras
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix develop .#ci --command dev release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
